/*
 * Copyright (c) 2013, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */
package com.oracle.max.vm.ext.graal.snippets;

import static com.oracle.graal.api.code.MemoryBarriers.*;
import static com.oracle.graal.nodes.extended.MembarNode.*;

import java.util.*;

import com.oracle.graal.api.code.*;
import com.oracle.graal.api.meta.*;
import com.oracle.graal.graph.*;
import com.oracle.graal.nodes.*;
import com.oracle.graal.nodes.extended.*;
import com.oracle.graal.nodes.java.*;
import com.oracle.graal.nodes.spi.*;
import com.oracle.graal.nodes.type.*;
import com.oracle.graal.replacements.*;
import com.oracle.graal.replacements.Snippet.ConstantParameter;
import com.oracle.graal.replacements.SnippetTemplate.*;
import com.oracle.max.vm.ext.graal.*;
import com.oracle.max.vm.ext.graal.nodes.*;
import com.sun.cri.ci.*;
import com.sun.cri.ri.*;
import com.sun.max.annotate.*;
import com.sun.max.vm.actor.member.*;
import com.sun.max.vm.classfile.constant.*;
import com.sun.max.vm.compiler.*;
import com.sun.max.vm.object.*;
import com.sun.max.vm.runtime.*;
import com.sun.max.vm.runtime.Snippets;

/**
 * Snippets for field access, resolved and unresolved. The unresolved field lowerings use similar code
 * generated by {@link T1X} and makes a runtime call to do the resolution. Ideally, the code
 * sequences would be shared, however, {@code T1X} does not do volatile handling in the template for
 * resolved fields (for some reason) and also uses {@code int} and casts for {@code boolean, byte, char, short} types
 * in the templates.
 *
 * When deoptimzation for Graal works, it might be better to follow the normal Graal expectation of deoptimizing the code
 * for unresolved fields, thus leaving the resolution to {@link T1X}.
 *
 * One possible improvement to unresolved field handling would be to inline the guard check.
 *
 * The resolved snippets are very simple and actually the same for instance fields and static fields,
 * as either the static tuple or the receiver is passed as the "object", so the signatures are identical.
 *
 * Unresolved snippets are more complex, as we can't access the static tuple until the resolution has occurred,
 * and the runtime calls in the (historic) {@link Snippets} class to do the resolution are different for static
 * and instance fields. So there are separate snippets for instance and static fields. There is also an intermediate
 * state where the field is resolved but the class may need to be initialized.
 *
 * Once the resolution/init is done, the resolved snippet can be invoked (as runtime code) to handle the field access.
 *
 * A note on naming. Although the bytecode names are {@code GET/PUT}, Graal uses {@code Load/Store} and does not distinguish static
 * loads by name, instead by the receiver field being {@code null}. We follow the Graal naming for the classes
 * that effect the lowering, but use the bytecode style names for the actual snippets and runtime entry methods.
 * Further we consistently use {@code Get#MODE#Field} where, {@code #MODE} is either {@code Instance} or {@code Static}.
 * Any action qualifier, e.g. {@code resolve} prefixes a name. The {@link Kind} of the access is used as a suffix,
 * e.g., {@code resolveGetStaticBoolean}.
 *
 * The {@code Object} field load/store operations may, depending on the {@link HeapScheme} in use, involve read/write
 * barriers. These may themselves involve loading fields from objects controlled by the {@link HeapScheme}, that
 * may be {@link CONSTANT_WHEN_NOT_ZERO} at runtime. The resolved field lowering handles this situation explicitly but there
 * is evidently an opportunity to transform the snippet on VM startup to replace the field access with the runtime constant.
 */
public class FieldSnippets extends SnippetLowerings {

    @HOSTED_ONLY
    public FieldSnippets(MetaAccessProvider runtime, Replacements replacements, TargetDescription targetDescription, Map<Class< ? extends Node>, LoweringProvider> lowerings) {
        super(runtime, replacements, targetDescription);
    }

    @Override
    @HOSTED_ONLY
    public void registerLowerings(MetaAccessProvider runtime, Replacements replacements, TargetDescription targetDescription, Map<Class< ? extends Node>, LoweringProvider> lowerings) {
        LoadFieldLowering loadFieldLowering = new LoadFieldLowering();
        StoreFieldLowering storeFieldLowering = new StoreFieldLowering();

        UnresolvedLoadFieldLowering unresolvedLoadFieldLowering = new UnresolvedLoadFieldLowering();
        UnresolvedStoreFieldLowering unresolvedStoreFieldLowering = new UnresolvedStoreFieldLowering();

        UnresolvedLoadFieldLowering unresolvedLoadStaticFieldLowering = new UnresolvedLoadFieldLowering();
        UnresolvedStoreFieldLowering unresolvedStoreStaticFieldLowering = new UnresolvedStoreFieldLowering();

        UnresolvedLoadFieldLowering loadHolderInitStaticFieldLowering = new UnresolvedLoadFieldLowering();
        UnresolvedStoreFieldLowering storeHolderInitStaticFieldLowering = new UnresolvedStoreFieldLowering();
        UnresolvedLoadFieldLowering loadHolderInitInstanceFieldLowering = new UnresolvedLoadFieldLowering();
        UnresolvedStoreFieldLowering storeHolderInitInstanceFieldLowering = new UnresolvedStoreFieldLowering();

        // Can only register one lowering class per node, so the static/init variants have to be handled in an ad hoc way
        unresolvedLoadFieldLowering.staticFieldLowering = unresolvedLoadStaticFieldLowering;
        unresolvedLoadFieldLowering.initHolderStaticFieldLowering = loadHolderInitStaticFieldLowering;
        unresolvedLoadFieldLowering.initHolderInstanceFieldLowering = loadHolderInitInstanceFieldLowering;

        unresolvedStoreFieldLowering.staticFieldLowering = unresolvedStoreStaticFieldLowering;
        unresolvedStoreFieldLowering.initHolderStaticFieldLowering = storeHolderInitStaticFieldLowering;
        unresolvedStoreFieldLowering.initHolderInstanceFieldLowering = storeHolderInitInstanceFieldLowering;


        addSnippets(loadFieldLowering, storeFieldLowering, unresolvedLoadFieldLowering, unresolvedStoreFieldLowering);


        lowerings.put(LoadFieldNode.class, loadFieldLowering);
        lowerings.put(StoreFieldNode.class, storeFieldLowering);
        lowerings.put(UnresolvedLoadFieldNode.class, unresolvedLoadFieldLowering);
        lowerings.put(UnresolvedStoreFieldNode.class, unresolvedStoreFieldLowering);
    }

    protected abstract class FieldLowering extends Lowering {
        protected final SnippetInfo[] snippets = new SnippetInfo[Kind.values().length];

        void setSnippet(Kind kind, SnippetInfo snippet) {
            snippets[kind.ordinal()] = snippet;
        }
    }

    protected abstract class ResolvedFieldLowering extends FieldLowering {

        void lower(AccessFieldNode node) {
            FieldActor fieldActor = (FieldActor) MaxResolvedJavaField.getRiResolvedField(node.field());
            /*
             * Check for access to fields that are CONSTANT_WHEN_NOT_ZERO with a constant receiver.
             * Most important for the biasedtableAddress of the CardTable for GenSSHeapScheme
             * May not be the best place to do this.
             */
            if (fieldActor.isConstantWhenNotZero() && node.object() != null && node.object().isConstant() &&
                            node.object().asConstant().isNonNull()) {
                CiConstant value = fieldActor.constantValue(ConstantMap.toCi(node.object().asConstant()));
                if (value != null) {
                    StructuredGraph graph = node.graph();
                    node.replaceAndDelete(graph.add(ConstantNode.forConstant(ConstantMap.toGraal(value), runtime, graph)));
                    return;
                }
            }
            boolean isStatic = node.isStatic();
            Arguments args = new Arguments(snippets[KindMap.toGraalKind(WordUtil.ciKind(fieldActor.kind, true)).ordinal()]);
            args.add("object", isStatic ? fieldActor.holder().staticTuple() : node.object());
            args.add("offset", fieldActor.offset());
            args.addConst("isVolatile", fieldActor.isVolatile());
            storeFieldArg(node, args);
            instantiate(node, args);
        }

        protected void storeFieldArg(AccessFieldNode node, Arguments args) {
        }

    }

    protected class LoadFieldLowering extends ResolvedFieldLowering implements LoweringProvider<LoadFieldNode> {

        @Override
        public void lower(LoadFieldNode node, LoweringTool tool) {
            lower(node);
        }

    }

    protected class StoreFieldLowering extends ResolvedFieldLowering implements LoweringProvider<StoreFieldNode> {

        @Override
        public void lower(StoreFieldNode node, LoweringTool tool) {
            lower(node);
        }

        @Override
        protected void storeFieldArg(AccessFieldNode node, Arguments args) {
            args.add("value", ((StoreFieldNode) node).value());
        }
    }

    protected class UnresolvedFieldLowering extends FieldLowering {
        /**
         * Holds the snippet methods for the static variants.
         */
        UnresolvedFieldLowering staticFieldLowering;
        /**
         * Holds the snippet for class initialization and static variant.
         */
        UnresolvedFieldLowering initHolderStaticFieldLowering;
        /**
         * Holds the snippet for class initialization and instance variant.
         */
        UnresolvedFieldLowering initHolderInstanceFieldLowering;

        void lower(UnresolvedAccessFieldNode node) {
            Arguments args;
            boolean isStatic = node.object() == null;
            int ord = node.kind().ordinal();
            RiField riField = MaxJavaField.getRiField(node.field());
            if (riField instanceof FieldActor) {
                // resolved but may need class initialization
                args = new Arguments(isStatic ? initHolderStaticFieldLowering.snippets[ord] : initHolderInstanceFieldLowering.snippets[ord]);
                args.add("f", riField);
            } else {
                UnresolvedField unresolvedField = (UnresolvedField) riField;
                ResolutionGuard.InPool guard = unresolvedField.constantPool.makeResolutionGuard(unresolvedField.cpi);
                args = new Arguments(isStatic ? staticFieldLowering.snippets[ord] : snippets[ord]);
                args.add("guard", guard);
            }
            if (!isStatic) {
                args.add("object", node.object());
            }
            storeFieldArg(node, args);
            instantiate(node, args);
        }

        protected void storeFieldArg(UnresolvedAccessFieldNode node, Arguments args) {
        }

    }

    protected class UnresolvedLoadFieldLowering extends UnresolvedFieldLowering implements LoweringProvider<UnresolvedLoadFieldNode> {

        @Override
        public void lower(UnresolvedLoadFieldNode node, LoweringTool tool) {
            lower(node);
        }

    }

    protected class UnresolvedStoreFieldLowering extends UnresolvedFieldLowering implements LoweringProvider<UnresolvedStoreFieldNode> {

        @Override
        public void lower(UnresolvedStoreFieldNode node, LoweringTool tool) {
            lower(node);
        }

        @Override
        protected void storeFieldArg(UnresolvedAccessFieldNode node, Arguments args) {
            args.add("value", ((UnresolvedStoreFieldNode) node).value());
        }
    }

// START GENERATED CODE
    @INLINE
    private static boolean getFieldBoolean(Object object, int offset, boolean isVolatile) {
        if (isVolatile) {
            memoryBarrier(JMM_PRE_VOLATILE_READ);
        }
        boolean result = TupleAccess.readBoolean(object, offset);
        if (isVolatile) {
            memoryBarrier(JMM_POST_VOLATILE_READ);
        }
        return result;
    }

    @INLINE
    private static void putFieldBoolean(Object object, int offset, boolean isVolatile, boolean value) {
        if (isVolatile) {
            memoryBarrier(JMM_PRE_VOLATILE_WRITE);
        }
        TupleAccess.writeBoolean(object, offset, value);
        if (isVolatile) {
            memoryBarrier(JMM_POST_VOLATILE_READ);
        }
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static boolean getFieldBooleanSnippet(Object object, int offset, @ConstantParameter boolean isVolatile) {
        return getFieldBoolean(object, offset, isVolatile);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static void putFieldBooleanSnippet(Object object, int offset, @ConstantParameter boolean isVolatile, boolean value) {
        putFieldBoolean(object, offset, isVolatile, value);
    }

    @SNIPPET_SLOWPATH
    private static boolean resolveAndGetInstanceFieldBoolean(ResolutionGuard.InPool guard, Object object) {
        FieldActor f = Snippets.resolveInstanceFieldForReading(guard);
        return holderInitAndGetInstanceFieldBoolean(f, object);
    }

    @SNIPPET_SLOWPATH
    private static boolean resolveAndGetStaticFieldBoolean(ResolutionGuard.InPool guard) {
        FieldActor f = Snippets.resolveStaticFieldForReading(guard);
        return holderInitAndGetStaticFieldBoolean(f);
    }

    @SNIPPET_SLOWPATH
    private static void resolveAndPutInstanceFieldBoolean(ResolutionGuard.InPool guard, Object object, boolean value) {
        FieldActor f = Snippets.resolveInstanceFieldForWriting(guard);
        holderInitAndPutInstanceFieldBoolean(f, object, value);
    }

    @SNIPPET_SLOWPATH
    private static void resolveAndPutStaticFieldBoolean(ResolutionGuard.InPool guard, boolean value) {
        FieldActor f = Snippets.resolveStaticFieldForWriting(guard);
        holderInitAndPutStaticFieldBoolean(f, value);
    }

    @SNIPPET_SLOWPATH
    private static boolean holderInitAndGetInstanceFieldBoolean(FieldActor f, Object object) {
        Snippets.makeHolderInitialized(f);
        return getFieldBoolean(object, f.offset(), f.isVolatile());
    }

    @SNIPPET_SLOWPATH
    private static boolean holderInitAndGetStaticFieldBoolean(FieldActor f) {
        Snippets.makeHolderInitialized(f);
        return getFieldBoolean(f.holder().staticTuple(), f.offset(), f.isVolatile());
    }

    @SNIPPET_SLOWPATH
    private static void holderInitAndPutInstanceFieldBoolean(FieldActor f, Object object, boolean value) {
        Snippets.makeHolderInitialized(f);
        putFieldBoolean(object, f.offset(), f.isVolatile(), value);
    }

    @SNIPPET_SLOWPATH
    private static void holderInitAndPutStaticFieldBoolean(FieldActor f, boolean value) {
        Snippets.makeHolderInitialized(f);
        putFieldBoolean(f.holder().staticTuple(), f.offset(), f.isVolatile(), value);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static boolean holderInitAndGetInstanceFieldBooleanSnippet(FieldActor f, Object object) {
        return holderInitAndGetInstanceFieldBoolean(f, object);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static boolean holderInitAndGetStaticFieldBooleanSnippet(FieldActor f) {
        return holderInitAndGetStaticFieldBoolean(f);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static void holderInitAndPutInstanceFieldBooleanSnippet(FieldActor f, Object object, boolean value) {
        holderInitAndPutInstanceFieldBoolean(f, object, value);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static void holderInitAndPutStaticFieldBooleanSnippet(FieldActor f, boolean value) {
        holderInitAndPutStaticFieldBoolean(f, value);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static boolean resolveAndGetInstanceFieldBooleanSnippet(ResolutionGuard.InPool guard, Object object) {
        return resolveAndGetInstanceFieldBoolean(guard, object);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static boolean resolveAndGetStaticFieldBooleanSnippet(ResolutionGuard.InPool guard) {
        return resolveAndGetStaticFieldBoolean(guard);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static void resolveAndPutInstanceFieldBooleanSnippet(ResolutionGuard.InPool guard, Object object, boolean value) {
        resolveAndPutInstanceFieldBoolean(guard, object, value);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static void resolveAndPutStaticFieldBooleanSnippet(ResolutionGuard.InPool guard, boolean value) {
        resolveAndPutStaticFieldBoolean(guard, value);
    }

    @INLINE
    private static byte getFieldByte(Object object, int offset, boolean isVolatile) {
        if (isVolatile) {
            memoryBarrier(JMM_PRE_VOLATILE_READ);
        }
        byte result = TupleAccess.readByte(object, offset);
        if (isVolatile) {
            memoryBarrier(JMM_POST_VOLATILE_READ);
        }
        return result;
    }

    @INLINE
    private static void putFieldByte(Object object, int offset, boolean isVolatile, byte value) {
        if (isVolatile) {
            memoryBarrier(JMM_PRE_VOLATILE_WRITE);
        }
        TupleAccess.writeByte(object, offset, value);
        if (isVolatile) {
            memoryBarrier(JMM_POST_VOLATILE_READ);
        }
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static byte getFieldByteSnippet(Object object, int offset, @ConstantParameter boolean isVolatile) {
        return getFieldByte(object, offset, isVolatile);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static void putFieldByteSnippet(Object object, int offset, @ConstantParameter boolean isVolatile, byte value) {
        putFieldByte(object, offset, isVolatile, value);
    }

    @SNIPPET_SLOWPATH
    private static byte resolveAndGetInstanceFieldByte(ResolutionGuard.InPool guard, Object object) {
        FieldActor f = Snippets.resolveInstanceFieldForReading(guard);
        return holderInitAndGetInstanceFieldByte(f, object);
    }

    @SNIPPET_SLOWPATH
    private static byte resolveAndGetStaticFieldByte(ResolutionGuard.InPool guard) {
        FieldActor f = Snippets.resolveStaticFieldForReading(guard);
        return holderInitAndGetStaticFieldByte(f);
    }

    @SNIPPET_SLOWPATH
    private static void resolveAndPutInstanceFieldByte(ResolutionGuard.InPool guard, Object object, byte value) {
        FieldActor f = Snippets.resolveInstanceFieldForWriting(guard);
        holderInitAndPutInstanceFieldByte(f, object, value);
    }

    @SNIPPET_SLOWPATH
    private static void resolveAndPutStaticFieldByte(ResolutionGuard.InPool guard, byte value) {
        FieldActor f = Snippets.resolveStaticFieldForWriting(guard);
        holderInitAndPutStaticFieldByte(f, value);
    }

    @SNIPPET_SLOWPATH
    private static byte holderInitAndGetInstanceFieldByte(FieldActor f, Object object) {
        Snippets.makeHolderInitialized(f);
        return getFieldByte(object, f.offset(), f.isVolatile());
    }

    @SNIPPET_SLOWPATH
    private static byte holderInitAndGetStaticFieldByte(FieldActor f) {
        Snippets.makeHolderInitialized(f);
        return getFieldByte(f.holder().staticTuple(), f.offset(), f.isVolatile());
    }

    @SNIPPET_SLOWPATH
    private static void holderInitAndPutInstanceFieldByte(FieldActor f, Object object, byte value) {
        Snippets.makeHolderInitialized(f);
        putFieldByte(object, f.offset(), f.isVolatile(), value);
    }

    @SNIPPET_SLOWPATH
    private static void holderInitAndPutStaticFieldByte(FieldActor f, byte value) {
        Snippets.makeHolderInitialized(f);
        putFieldByte(f.holder().staticTuple(), f.offset(), f.isVolatile(), value);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static byte holderInitAndGetInstanceFieldByteSnippet(FieldActor f, Object object) {
        return holderInitAndGetInstanceFieldByte(f, object);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static byte holderInitAndGetStaticFieldByteSnippet(FieldActor f) {
        return holderInitAndGetStaticFieldByte(f);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static void holderInitAndPutInstanceFieldByteSnippet(FieldActor f, Object object, byte value) {
        holderInitAndPutInstanceFieldByte(f, object, value);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static void holderInitAndPutStaticFieldByteSnippet(FieldActor f, byte value) {
        holderInitAndPutStaticFieldByte(f, value);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static byte resolveAndGetInstanceFieldByteSnippet(ResolutionGuard.InPool guard, Object object) {
        return resolveAndGetInstanceFieldByte(guard, object);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static byte resolveAndGetStaticFieldByteSnippet(ResolutionGuard.InPool guard) {
        return resolveAndGetStaticFieldByte(guard);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static void resolveAndPutInstanceFieldByteSnippet(ResolutionGuard.InPool guard, Object object, byte value) {
        resolveAndPutInstanceFieldByte(guard, object, value);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static void resolveAndPutStaticFieldByteSnippet(ResolutionGuard.InPool guard, byte value) {
        resolveAndPutStaticFieldByte(guard, value);
    }

    @INLINE
    private static short getFieldShort(Object object, int offset, boolean isVolatile) {
        if (isVolatile) {
            memoryBarrier(JMM_PRE_VOLATILE_READ);
        }
        short result = TupleAccess.readShort(object, offset);
        if (isVolatile) {
            memoryBarrier(JMM_POST_VOLATILE_READ);
        }
        return result;
    }

    @INLINE
    private static void putFieldShort(Object object, int offset, boolean isVolatile, short value) {
        if (isVolatile) {
            memoryBarrier(JMM_PRE_VOLATILE_WRITE);
        }
        TupleAccess.writeShort(object, offset, value);
        if (isVolatile) {
            memoryBarrier(JMM_POST_VOLATILE_READ);
        }
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static short getFieldShortSnippet(Object object, int offset, @ConstantParameter boolean isVolatile) {
        return getFieldShort(object, offset, isVolatile);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static void putFieldShortSnippet(Object object, int offset, @ConstantParameter boolean isVolatile, short value) {
        putFieldShort(object, offset, isVolatile, value);
    }

    @SNIPPET_SLOWPATH
    private static short resolveAndGetInstanceFieldShort(ResolutionGuard.InPool guard, Object object) {
        FieldActor f = Snippets.resolveInstanceFieldForReading(guard);
        return holderInitAndGetInstanceFieldShort(f, object);
    }

    @SNIPPET_SLOWPATH
    private static short resolveAndGetStaticFieldShort(ResolutionGuard.InPool guard) {
        FieldActor f = Snippets.resolveStaticFieldForReading(guard);
        return holderInitAndGetStaticFieldShort(f);
    }

    @SNIPPET_SLOWPATH
    private static void resolveAndPutInstanceFieldShort(ResolutionGuard.InPool guard, Object object, short value) {
        FieldActor f = Snippets.resolveInstanceFieldForWriting(guard);
        holderInitAndPutInstanceFieldShort(f, object, value);
    }

    @SNIPPET_SLOWPATH
    private static void resolveAndPutStaticFieldShort(ResolutionGuard.InPool guard, short value) {
        FieldActor f = Snippets.resolveStaticFieldForWriting(guard);
        holderInitAndPutStaticFieldShort(f, value);
    }

    @SNIPPET_SLOWPATH
    private static short holderInitAndGetInstanceFieldShort(FieldActor f, Object object) {
        Snippets.makeHolderInitialized(f);
        return getFieldShort(object, f.offset(), f.isVolatile());
    }

    @SNIPPET_SLOWPATH
    private static short holderInitAndGetStaticFieldShort(FieldActor f) {
        Snippets.makeHolderInitialized(f);
        return getFieldShort(f.holder().staticTuple(), f.offset(), f.isVolatile());
    }

    @SNIPPET_SLOWPATH
    private static void holderInitAndPutInstanceFieldShort(FieldActor f, Object object, short value) {
        Snippets.makeHolderInitialized(f);
        putFieldShort(object, f.offset(), f.isVolatile(), value);
    }

    @SNIPPET_SLOWPATH
    private static void holderInitAndPutStaticFieldShort(FieldActor f, short value) {
        Snippets.makeHolderInitialized(f);
        putFieldShort(f.holder().staticTuple(), f.offset(), f.isVolatile(), value);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static short holderInitAndGetInstanceFieldShortSnippet(FieldActor f, Object object) {
        return holderInitAndGetInstanceFieldShort(f, object);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static short holderInitAndGetStaticFieldShortSnippet(FieldActor f) {
        return holderInitAndGetStaticFieldShort(f);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static void holderInitAndPutInstanceFieldShortSnippet(FieldActor f, Object object, short value) {
        holderInitAndPutInstanceFieldShort(f, object, value);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static void holderInitAndPutStaticFieldShortSnippet(FieldActor f, short value) {
        holderInitAndPutStaticFieldShort(f, value);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static short resolveAndGetInstanceFieldShortSnippet(ResolutionGuard.InPool guard, Object object) {
        return resolveAndGetInstanceFieldShort(guard, object);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static short resolveAndGetStaticFieldShortSnippet(ResolutionGuard.InPool guard) {
        return resolveAndGetStaticFieldShort(guard);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static void resolveAndPutInstanceFieldShortSnippet(ResolutionGuard.InPool guard, Object object, short value) {
        resolveAndPutInstanceFieldShort(guard, object, value);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static void resolveAndPutStaticFieldShortSnippet(ResolutionGuard.InPool guard, short value) {
        resolveAndPutStaticFieldShort(guard, value);
    }

    @INLINE
    private static char getFieldChar(Object object, int offset, boolean isVolatile) {
        if (isVolatile) {
            memoryBarrier(JMM_PRE_VOLATILE_READ);
        }
        char result = TupleAccess.readChar(object, offset);
        if (isVolatile) {
            memoryBarrier(JMM_POST_VOLATILE_READ);
        }
        return result;
    }

    @INLINE
    private static void putFieldChar(Object object, int offset, boolean isVolatile, char value) {
        if (isVolatile) {
            memoryBarrier(JMM_PRE_VOLATILE_WRITE);
        }
        TupleAccess.writeChar(object, offset, value);
        if (isVolatile) {
            memoryBarrier(JMM_POST_VOLATILE_READ);
        }
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static char getFieldCharSnippet(Object object, int offset, @ConstantParameter boolean isVolatile) {
        return getFieldChar(object, offset, isVolatile);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static void putFieldCharSnippet(Object object, int offset, @ConstantParameter boolean isVolatile, char value) {
        putFieldChar(object, offset, isVolatile, value);
    }

    @SNIPPET_SLOWPATH
    private static char resolveAndGetInstanceFieldChar(ResolutionGuard.InPool guard, Object object) {
        FieldActor f = Snippets.resolveInstanceFieldForReading(guard);
        return holderInitAndGetInstanceFieldChar(f, object);
    }

    @SNIPPET_SLOWPATH
    private static char resolveAndGetStaticFieldChar(ResolutionGuard.InPool guard) {
        FieldActor f = Snippets.resolveStaticFieldForReading(guard);
        return holderInitAndGetStaticFieldChar(f);
    }

    @SNIPPET_SLOWPATH
    private static void resolveAndPutInstanceFieldChar(ResolutionGuard.InPool guard, Object object, char value) {
        FieldActor f = Snippets.resolveInstanceFieldForWriting(guard);
        holderInitAndPutInstanceFieldChar(f, object, value);
    }

    @SNIPPET_SLOWPATH
    private static void resolveAndPutStaticFieldChar(ResolutionGuard.InPool guard, char value) {
        FieldActor f = Snippets.resolveStaticFieldForWriting(guard);
        holderInitAndPutStaticFieldChar(f, value);
    }

    @SNIPPET_SLOWPATH
    private static char holderInitAndGetInstanceFieldChar(FieldActor f, Object object) {
        Snippets.makeHolderInitialized(f);
        return getFieldChar(object, f.offset(), f.isVolatile());
    }

    @SNIPPET_SLOWPATH
    private static char holderInitAndGetStaticFieldChar(FieldActor f) {
        Snippets.makeHolderInitialized(f);
        return getFieldChar(f.holder().staticTuple(), f.offset(), f.isVolatile());
    }

    @SNIPPET_SLOWPATH
    private static void holderInitAndPutInstanceFieldChar(FieldActor f, Object object, char value) {
        Snippets.makeHolderInitialized(f);
        putFieldChar(object, f.offset(), f.isVolatile(), value);
    }

    @SNIPPET_SLOWPATH
    private static void holderInitAndPutStaticFieldChar(FieldActor f, char value) {
        Snippets.makeHolderInitialized(f);
        putFieldChar(f.holder().staticTuple(), f.offset(), f.isVolatile(), value);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static char holderInitAndGetInstanceFieldCharSnippet(FieldActor f, Object object) {
        return holderInitAndGetInstanceFieldChar(f, object);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static char holderInitAndGetStaticFieldCharSnippet(FieldActor f) {
        return holderInitAndGetStaticFieldChar(f);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static void holderInitAndPutInstanceFieldCharSnippet(FieldActor f, Object object, char value) {
        holderInitAndPutInstanceFieldChar(f, object, value);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static void holderInitAndPutStaticFieldCharSnippet(FieldActor f, char value) {
        holderInitAndPutStaticFieldChar(f, value);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static char resolveAndGetInstanceFieldCharSnippet(ResolutionGuard.InPool guard, Object object) {
        return resolveAndGetInstanceFieldChar(guard, object);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static char resolveAndGetStaticFieldCharSnippet(ResolutionGuard.InPool guard) {
        return resolveAndGetStaticFieldChar(guard);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static void resolveAndPutInstanceFieldCharSnippet(ResolutionGuard.InPool guard, Object object, char value) {
        resolveAndPutInstanceFieldChar(guard, object, value);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static void resolveAndPutStaticFieldCharSnippet(ResolutionGuard.InPool guard, char value) {
        resolveAndPutStaticFieldChar(guard, value);
    }

    @INLINE
    private static int getFieldInt(Object object, int offset, boolean isVolatile) {
        if (isVolatile) {
            memoryBarrier(JMM_PRE_VOLATILE_READ);
        }
        int result = TupleAccess.readInt(object, offset);
        if (isVolatile) {
            memoryBarrier(JMM_POST_VOLATILE_READ);
        }
        return result;
    }

    @INLINE
    private static void putFieldInt(Object object, int offset, boolean isVolatile, int value) {
        if (isVolatile) {
            memoryBarrier(JMM_PRE_VOLATILE_WRITE);
        }
        TupleAccess.writeInt(object, offset, value);
        if (isVolatile) {
            memoryBarrier(JMM_POST_VOLATILE_READ);
        }
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static int getFieldIntSnippet(Object object, int offset, @ConstantParameter boolean isVolatile) {
        return getFieldInt(object, offset, isVolatile);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static void putFieldIntSnippet(Object object, int offset, @ConstantParameter boolean isVolatile, int value) {
        putFieldInt(object, offset, isVolatile, value);
    }

    @SNIPPET_SLOWPATH
    private static int resolveAndGetInstanceFieldInt(ResolutionGuard.InPool guard, Object object) {
        FieldActor f = Snippets.resolveInstanceFieldForReading(guard);
        return holderInitAndGetInstanceFieldInt(f, object);
    }

    @SNIPPET_SLOWPATH
    private static int resolveAndGetStaticFieldInt(ResolutionGuard.InPool guard) {
        FieldActor f = Snippets.resolveStaticFieldForReading(guard);
        return holderInitAndGetStaticFieldInt(f);
    }

    @SNIPPET_SLOWPATH
    private static void resolveAndPutInstanceFieldInt(ResolutionGuard.InPool guard, Object object, int value) {
        FieldActor f = Snippets.resolveInstanceFieldForWriting(guard);
        holderInitAndPutInstanceFieldInt(f, object, value);
    }

    @SNIPPET_SLOWPATH
    private static void resolveAndPutStaticFieldInt(ResolutionGuard.InPool guard, int value) {
        FieldActor f = Snippets.resolveStaticFieldForWriting(guard);
        holderInitAndPutStaticFieldInt(f, value);
    }

    @SNIPPET_SLOWPATH
    private static int holderInitAndGetInstanceFieldInt(FieldActor f, Object object) {
        Snippets.makeHolderInitialized(f);
        return getFieldInt(object, f.offset(), f.isVolatile());
    }

    @SNIPPET_SLOWPATH
    private static int holderInitAndGetStaticFieldInt(FieldActor f) {
        Snippets.makeHolderInitialized(f);
        return getFieldInt(f.holder().staticTuple(), f.offset(), f.isVolatile());
    }

    @SNIPPET_SLOWPATH
    private static void holderInitAndPutInstanceFieldInt(FieldActor f, Object object, int value) {
        Snippets.makeHolderInitialized(f);
        putFieldInt(object, f.offset(), f.isVolatile(), value);
    }

    @SNIPPET_SLOWPATH
    private static void holderInitAndPutStaticFieldInt(FieldActor f, int value) {
        Snippets.makeHolderInitialized(f);
        putFieldInt(f.holder().staticTuple(), f.offset(), f.isVolatile(), value);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static int holderInitAndGetInstanceFieldIntSnippet(FieldActor f, Object object) {
        return holderInitAndGetInstanceFieldInt(f, object);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static int holderInitAndGetStaticFieldIntSnippet(FieldActor f) {
        return holderInitAndGetStaticFieldInt(f);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static void holderInitAndPutInstanceFieldIntSnippet(FieldActor f, Object object, int value) {
        holderInitAndPutInstanceFieldInt(f, object, value);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static void holderInitAndPutStaticFieldIntSnippet(FieldActor f, int value) {
        holderInitAndPutStaticFieldInt(f, value);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static int resolveAndGetInstanceFieldIntSnippet(ResolutionGuard.InPool guard, Object object) {
        return resolveAndGetInstanceFieldInt(guard, object);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static int resolveAndGetStaticFieldIntSnippet(ResolutionGuard.InPool guard) {
        return resolveAndGetStaticFieldInt(guard);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static void resolveAndPutInstanceFieldIntSnippet(ResolutionGuard.InPool guard, Object object, int value) {
        resolveAndPutInstanceFieldInt(guard, object, value);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static void resolveAndPutStaticFieldIntSnippet(ResolutionGuard.InPool guard, int value) {
        resolveAndPutStaticFieldInt(guard, value);
    }

    @INLINE
    private static float getFieldFloat(Object object, int offset, boolean isVolatile) {
        if (isVolatile) {
            memoryBarrier(JMM_PRE_VOLATILE_READ);
        }
        float result = TupleAccess.readFloat(object, offset);
        if (isVolatile) {
            memoryBarrier(JMM_POST_VOLATILE_READ);
        }
        return result;
    }

    @INLINE
    private static void putFieldFloat(Object object, int offset, boolean isVolatile, float value) {
        if (isVolatile) {
            memoryBarrier(JMM_PRE_VOLATILE_WRITE);
        }
        TupleAccess.writeFloat(object, offset, value);
        if (isVolatile) {
            memoryBarrier(JMM_POST_VOLATILE_READ);
        }
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static float getFieldFloatSnippet(Object object, int offset, @ConstantParameter boolean isVolatile) {
        return getFieldFloat(object, offset, isVolatile);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static void putFieldFloatSnippet(Object object, int offset, @ConstantParameter boolean isVolatile, float value) {
        putFieldFloat(object, offset, isVolatile, value);
    }

    @SNIPPET_SLOWPATH
    private static float resolveAndGetInstanceFieldFloat(ResolutionGuard.InPool guard, Object object) {
        FieldActor f = Snippets.resolveInstanceFieldForReading(guard);
        return holderInitAndGetInstanceFieldFloat(f, object);
    }

    @SNIPPET_SLOWPATH
    private static float resolveAndGetStaticFieldFloat(ResolutionGuard.InPool guard) {
        FieldActor f = Snippets.resolveStaticFieldForReading(guard);
        return holderInitAndGetStaticFieldFloat(f);
    }

    @SNIPPET_SLOWPATH
    private static void resolveAndPutInstanceFieldFloat(ResolutionGuard.InPool guard, Object object, float value) {
        FieldActor f = Snippets.resolveInstanceFieldForWriting(guard);
        holderInitAndPutInstanceFieldFloat(f, object, value);
    }

    @SNIPPET_SLOWPATH
    private static void resolveAndPutStaticFieldFloat(ResolutionGuard.InPool guard, float value) {
        FieldActor f = Snippets.resolveStaticFieldForWriting(guard);
        holderInitAndPutStaticFieldFloat(f, value);
    }

    @SNIPPET_SLOWPATH
    private static float holderInitAndGetInstanceFieldFloat(FieldActor f, Object object) {
        Snippets.makeHolderInitialized(f);
        return getFieldFloat(object, f.offset(), f.isVolatile());
    }

    @SNIPPET_SLOWPATH
    private static float holderInitAndGetStaticFieldFloat(FieldActor f) {
        Snippets.makeHolderInitialized(f);
        return getFieldFloat(f.holder().staticTuple(), f.offset(), f.isVolatile());
    }

    @SNIPPET_SLOWPATH
    private static void holderInitAndPutInstanceFieldFloat(FieldActor f, Object object, float value) {
        Snippets.makeHolderInitialized(f);
        putFieldFloat(object, f.offset(), f.isVolatile(), value);
    }

    @SNIPPET_SLOWPATH
    private static void holderInitAndPutStaticFieldFloat(FieldActor f, float value) {
        Snippets.makeHolderInitialized(f);
        putFieldFloat(f.holder().staticTuple(), f.offset(), f.isVolatile(), value);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static float holderInitAndGetInstanceFieldFloatSnippet(FieldActor f, Object object) {
        return holderInitAndGetInstanceFieldFloat(f, object);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static float holderInitAndGetStaticFieldFloatSnippet(FieldActor f) {
        return holderInitAndGetStaticFieldFloat(f);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static void holderInitAndPutInstanceFieldFloatSnippet(FieldActor f, Object object, float value) {
        holderInitAndPutInstanceFieldFloat(f, object, value);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static void holderInitAndPutStaticFieldFloatSnippet(FieldActor f, float value) {
        holderInitAndPutStaticFieldFloat(f, value);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static float resolveAndGetInstanceFieldFloatSnippet(ResolutionGuard.InPool guard, Object object) {
        return resolveAndGetInstanceFieldFloat(guard, object);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static float resolveAndGetStaticFieldFloatSnippet(ResolutionGuard.InPool guard) {
        return resolveAndGetStaticFieldFloat(guard);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static void resolveAndPutInstanceFieldFloatSnippet(ResolutionGuard.InPool guard, Object object, float value) {
        resolveAndPutInstanceFieldFloat(guard, object, value);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static void resolveAndPutStaticFieldFloatSnippet(ResolutionGuard.InPool guard, float value) {
        resolveAndPutStaticFieldFloat(guard, value);
    }

    @INLINE
    private static long getFieldLong(Object object, int offset, boolean isVolatile) {
        if (isVolatile) {
            memoryBarrier(JMM_PRE_VOLATILE_READ);
        }
        long result = TupleAccess.readLong(object, offset);
        if (isVolatile) {
            memoryBarrier(JMM_POST_VOLATILE_READ);
        }
        return result;
    }

    @INLINE
    private static void putFieldLong(Object object, int offset, boolean isVolatile, long value) {
        if (isVolatile) {
            memoryBarrier(JMM_PRE_VOLATILE_WRITE);
        }
        TupleAccess.writeLong(object, offset, value);
        if (isVolatile) {
            memoryBarrier(JMM_POST_VOLATILE_READ);
        }
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static long getFieldLongSnippet(Object object, int offset, @ConstantParameter boolean isVolatile) {
        return getFieldLong(object, offset, isVolatile);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static void putFieldLongSnippet(Object object, int offset, @ConstantParameter boolean isVolatile, long value) {
        putFieldLong(object, offset, isVolatile, value);
    }

    @SNIPPET_SLOWPATH
    private static long resolveAndGetInstanceFieldLong(ResolutionGuard.InPool guard, Object object) {
        FieldActor f = Snippets.resolveInstanceFieldForReading(guard);
        return holderInitAndGetInstanceFieldLong(f, object);
    }

    @SNIPPET_SLOWPATH
    private static long resolveAndGetStaticFieldLong(ResolutionGuard.InPool guard) {
        FieldActor f = Snippets.resolveStaticFieldForReading(guard);
        return holderInitAndGetStaticFieldLong(f);
    }

    @SNIPPET_SLOWPATH
    private static void resolveAndPutInstanceFieldLong(ResolutionGuard.InPool guard, Object object, long value) {
        FieldActor f = Snippets.resolveInstanceFieldForWriting(guard);
        holderInitAndPutInstanceFieldLong(f, object, value);
    }

    @SNIPPET_SLOWPATH
    private static void resolveAndPutStaticFieldLong(ResolutionGuard.InPool guard, long value) {
        FieldActor f = Snippets.resolveStaticFieldForWriting(guard);
        holderInitAndPutStaticFieldLong(f, value);
    }

    @SNIPPET_SLOWPATH
    private static long holderInitAndGetInstanceFieldLong(FieldActor f, Object object) {
        Snippets.makeHolderInitialized(f);
        return getFieldLong(object, f.offset(), f.isVolatile());
    }

    @SNIPPET_SLOWPATH
    private static long holderInitAndGetStaticFieldLong(FieldActor f) {
        Snippets.makeHolderInitialized(f);
        return getFieldLong(f.holder().staticTuple(), f.offset(), f.isVolatile());
    }

    @SNIPPET_SLOWPATH
    private static void holderInitAndPutInstanceFieldLong(FieldActor f, Object object, long value) {
        Snippets.makeHolderInitialized(f);
        putFieldLong(object, f.offset(), f.isVolatile(), value);
    }

    @SNIPPET_SLOWPATH
    private static void holderInitAndPutStaticFieldLong(FieldActor f, long value) {
        Snippets.makeHolderInitialized(f);
        putFieldLong(f.holder().staticTuple(), f.offset(), f.isVolatile(), value);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static long holderInitAndGetInstanceFieldLongSnippet(FieldActor f, Object object) {
        return holderInitAndGetInstanceFieldLong(f, object);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static long holderInitAndGetStaticFieldLongSnippet(FieldActor f) {
        return holderInitAndGetStaticFieldLong(f);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static void holderInitAndPutInstanceFieldLongSnippet(FieldActor f, Object object, long value) {
        holderInitAndPutInstanceFieldLong(f, object, value);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static void holderInitAndPutStaticFieldLongSnippet(FieldActor f, long value) {
        holderInitAndPutStaticFieldLong(f, value);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static long resolveAndGetInstanceFieldLongSnippet(ResolutionGuard.InPool guard, Object object) {
        return resolveAndGetInstanceFieldLong(guard, object);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static long resolveAndGetStaticFieldLongSnippet(ResolutionGuard.InPool guard) {
        return resolveAndGetStaticFieldLong(guard);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static void resolveAndPutInstanceFieldLongSnippet(ResolutionGuard.InPool guard, Object object, long value) {
        resolveAndPutInstanceFieldLong(guard, object, value);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static void resolveAndPutStaticFieldLongSnippet(ResolutionGuard.InPool guard, long value) {
        resolveAndPutStaticFieldLong(guard, value);
    }

    @INLINE
    private static double getFieldDouble(Object object, int offset, boolean isVolatile) {
        if (isVolatile) {
            memoryBarrier(JMM_PRE_VOLATILE_READ);
        }
        double result = TupleAccess.readDouble(object, offset);
        if (isVolatile) {
            memoryBarrier(JMM_POST_VOLATILE_READ);
        }
        return result;
    }

    @INLINE
    private static void putFieldDouble(Object object, int offset, boolean isVolatile, double value) {
        if (isVolatile) {
            memoryBarrier(JMM_PRE_VOLATILE_WRITE);
        }
        TupleAccess.writeDouble(object, offset, value);
        if (isVolatile) {
            memoryBarrier(JMM_POST_VOLATILE_READ);
        }
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static double getFieldDoubleSnippet(Object object, int offset, @ConstantParameter boolean isVolatile) {
        return getFieldDouble(object, offset, isVolatile);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static void putFieldDoubleSnippet(Object object, int offset, @ConstantParameter boolean isVolatile, double value) {
        putFieldDouble(object, offset, isVolatile, value);
    }

    @SNIPPET_SLOWPATH
    private static double resolveAndGetInstanceFieldDouble(ResolutionGuard.InPool guard, Object object) {
        FieldActor f = Snippets.resolveInstanceFieldForReading(guard);
        return holderInitAndGetInstanceFieldDouble(f, object);
    }

    @SNIPPET_SLOWPATH
    private static double resolveAndGetStaticFieldDouble(ResolutionGuard.InPool guard) {
        FieldActor f = Snippets.resolveStaticFieldForReading(guard);
        return holderInitAndGetStaticFieldDouble(f);
    }

    @SNIPPET_SLOWPATH
    private static void resolveAndPutInstanceFieldDouble(ResolutionGuard.InPool guard, Object object, double value) {
        FieldActor f = Snippets.resolveInstanceFieldForWriting(guard);
        holderInitAndPutInstanceFieldDouble(f, object, value);
    }

    @SNIPPET_SLOWPATH
    private static void resolveAndPutStaticFieldDouble(ResolutionGuard.InPool guard, double value) {
        FieldActor f = Snippets.resolveStaticFieldForWriting(guard);
        holderInitAndPutStaticFieldDouble(f, value);
    }

    @SNIPPET_SLOWPATH
    private static double holderInitAndGetInstanceFieldDouble(FieldActor f, Object object) {
        Snippets.makeHolderInitialized(f);
        return getFieldDouble(object, f.offset(), f.isVolatile());
    }

    @SNIPPET_SLOWPATH
    private static double holderInitAndGetStaticFieldDouble(FieldActor f) {
        Snippets.makeHolderInitialized(f);
        return getFieldDouble(f.holder().staticTuple(), f.offset(), f.isVolatile());
    }

    @SNIPPET_SLOWPATH
    private static void holderInitAndPutInstanceFieldDouble(FieldActor f, Object object, double value) {
        Snippets.makeHolderInitialized(f);
        putFieldDouble(object, f.offset(), f.isVolatile(), value);
    }

    @SNIPPET_SLOWPATH
    private static void holderInitAndPutStaticFieldDouble(FieldActor f, double value) {
        Snippets.makeHolderInitialized(f);
        putFieldDouble(f.holder().staticTuple(), f.offset(), f.isVolatile(), value);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static double holderInitAndGetInstanceFieldDoubleSnippet(FieldActor f, Object object) {
        return holderInitAndGetInstanceFieldDouble(f, object);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static double holderInitAndGetStaticFieldDoubleSnippet(FieldActor f) {
        return holderInitAndGetStaticFieldDouble(f);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static void holderInitAndPutInstanceFieldDoubleSnippet(FieldActor f, Object object, double value) {
        holderInitAndPutInstanceFieldDouble(f, object, value);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static void holderInitAndPutStaticFieldDoubleSnippet(FieldActor f, double value) {
        holderInitAndPutStaticFieldDouble(f, value);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static double resolveAndGetInstanceFieldDoubleSnippet(ResolutionGuard.InPool guard, Object object) {
        return resolveAndGetInstanceFieldDouble(guard, object);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static double resolveAndGetStaticFieldDoubleSnippet(ResolutionGuard.InPool guard) {
        return resolveAndGetStaticFieldDouble(guard);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static void resolveAndPutInstanceFieldDoubleSnippet(ResolutionGuard.InPool guard, Object object, double value) {
        resolveAndPutInstanceFieldDouble(guard, object, value);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static void resolveAndPutStaticFieldDoubleSnippet(ResolutionGuard.InPool guard, double value) {
        resolveAndPutStaticFieldDouble(guard, value);
    }

    @INLINE
    private static Object getFieldObject(Object object, int offset, boolean isVolatile) {
        if (isVolatile) {
            memoryBarrier(JMM_PRE_VOLATILE_READ);
        }
        Object result = TupleAccess.readObject(object, offset);
        if (isVolatile) {
            memoryBarrier(JMM_POST_VOLATILE_READ);
        }
        return result;
    }

    @INLINE
    private static void putFieldObject(Object object, int offset, boolean isVolatile, Object value) {
        if (isVolatile) {
            memoryBarrier(JMM_PRE_VOLATILE_WRITE);
        }
        TupleAccess.writeObject(object, offset, value);
        if (isVolatile) {
            memoryBarrier(JMM_POST_VOLATILE_READ);
        }
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static Object getFieldObjectSnippet(Object object, int offset, @ConstantParameter boolean isVolatile) {
        return UnsafeCastNode.unsafeCast(getFieldObject(object, offset, isVolatile), StampFactory.forNodeIntrinsic());
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static void putFieldObjectSnippet(Object object, int offset, @ConstantParameter boolean isVolatile, Object value) {
        putFieldObject(object, offset, isVolatile, value);
    }

    @SNIPPET_SLOWPATH
    private static Object resolveAndGetInstanceFieldObject(ResolutionGuard.InPool guard, Object object) {
        FieldActor f = Snippets.resolveInstanceFieldForReading(guard);
        return holderInitAndGetInstanceFieldObject(f, object);
    }

    @SNIPPET_SLOWPATH
    private static Object resolveAndGetStaticFieldObject(ResolutionGuard.InPool guard) {
        FieldActor f = Snippets.resolveStaticFieldForReading(guard);
        return holderInitAndGetStaticFieldObject(f);
    }

    @SNIPPET_SLOWPATH
    private static void resolveAndPutInstanceFieldObject(ResolutionGuard.InPool guard, Object object, Object value) {
        FieldActor f = Snippets.resolveInstanceFieldForWriting(guard);
        holderInitAndPutInstanceFieldObject(f, object, value);
    }

    @SNIPPET_SLOWPATH
    private static void resolveAndPutStaticFieldObject(ResolutionGuard.InPool guard, Object value) {
        FieldActor f = Snippets.resolveStaticFieldForWriting(guard);
        holderInitAndPutStaticFieldObject(f, value);
    }

    @SNIPPET_SLOWPATH
    private static Object holderInitAndGetInstanceFieldObject(FieldActor f, Object object) {
        Snippets.makeHolderInitialized(f);
        return getFieldObject(object, f.offset(), f.isVolatile());
    }

    @SNIPPET_SLOWPATH
    private static Object holderInitAndGetStaticFieldObject(FieldActor f) {
        Snippets.makeHolderInitialized(f);
        return getFieldObject(f.holder().staticTuple(), f.offset(), f.isVolatile());
    }

    @SNIPPET_SLOWPATH
    private static void holderInitAndPutInstanceFieldObject(FieldActor f, Object object, Object value) {
        Snippets.makeHolderInitialized(f);
        putFieldObject(object, f.offset(), f.isVolatile(), value);
    }

    @SNIPPET_SLOWPATH
    private static void holderInitAndPutStaticFieldObject(FieldActor f, Object value) {
        Snippets.makeHolderInitialized(f);
        putFieldObject(f.holder().staticTuple(), f.offset(), f.isVolatile(), value);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static Object holderInitAndGetInstanceFieldObjectSnippet(FieldActor f, Object object) {
        return UnsafeCastNode.unsafeCast(holderInitAndGetInstanceFieldObject(f, object), StampFactory.forNodeIntrinsic());
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static Object holderInitAndGetStaticFieldObjectSnippet(FieldActor f) {
        return UnsafeCastNode.unsafeCast(holderInitAndGetStaticFieldObject(f), StampFactory.forNodeIntrinsic());
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static void holderInitAndPutInstanceFieldObjectSnippet(FieldActor f, Object object, Object value) {
        holderInitAndPutInstanceFieldObject(f, object, value);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static void holderInitAndPutStaticFieldObjectSnippet(FieldActor f, Object value) {
        holderInitAndPutStaticFieldObject(f, value);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static Object resolveAndGetInstanceFieldObjectSnippet(ResolutionGuard.InPool guard, Object object) {
        return UnsafeCastNode.unsafeCast(resolveAndGetInstanceFieldObject(guard, object), StampFactory.forNodeIntrinsic());
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static Object resolveAndGetStaticFieldObjectSnippet(ResolutionGuard.InPool guard) {
        return UnsafeCastNode.unsafeCast(resolveAndGetStaticFieldObject(guard), StampFactory.forNodeIntrinsic());
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static void resolveAndPutInstanceFieldObjectSnippet(ResolutionGuard.InPool guard, Object object, Object value) {
        resolveAndPutInstanceFieldObject(guard, object, value);
    }

    @Snippet(inlining = MaxSnippetInliningPolicy.class)
    private static void resolveAndPutStaticFieldObjectSnippet(ResolutionGuard.InPool guard, Object value) {
        resolveAndPutStaticFieldObject(guard, value);
    }

    @HOSTED_ONLY
    private void addSnippets(
            LoadFieldLowering loadFieldLowering, StoreFieldLowering storeFieldLowering,
            UnresolvedLoadFieldLowering loadUnresolvedFieldLowering, UnresolvedStoreFieldLowering storeUnresolvedFieldLowering) {
        loadFieldLowering.setSnippet(Kind.Boolean, snippet(FieldSnippets.class, "getFieldBooleanSnippet"));
        storeFieldLowering.setSnippet(Kind.Boolean, snippet(FieldSnippets.class, "putFieldBooleanSnippet"));
        loadUnresolvedFieldLowering.setSnippet(Kind.Boolean, snippet(FieldSnippets.class, "resolveAndGetInstanceFieldBooleanSnippet"));
        loadUnresolvedFieldLowering.staticFieldLowering.setSnippet(Kind.Boolean, snippet(FieldSnippets.class, "resolveAndGetStaticFieldBooleanSnippet"));
        storeUnresolvedFieldLowering.setSnippet(Kind.Boolean, snippet(FieldSnippets.class, "resolveAndPutInstanceFieldBooleanSnippet"));
        storeUnresolvedFieldLowering.staticFieldLowering.setSnippet(Kind.Boolean, snippet(FieldSnippets.class, "resolveAndPutStaticFieldBooleanSnippet"));
        loadUnresolvedFieldLowering.initHolderInstanceFieldLowering.setSnippet(Kind.Boolean, snippet(FieldSnippets.class, "holderInitAndGetInstanceFieldBooleanSnippet"));
        loadUnresolvedFieldLowering.initHolderStaticFieldLowering.setSnippet(Kind.Boolean, snippet(FieldSnippets.class, "holderInitAndGetStaticFieldBooleanSnippet"));
        storeUnresolvedFieldLowering.initHolderInstanceFieldLowering.setSnippet(Kind.Boolean, snippet(FieldSnippets.class, "holderInitAndPutInstanceFieldBooleanSnippet"));
        storeUnresolvedFieldLowering.initHolderStaticFieldLowering.setSnippet(Kind.Boolean, snippet(FieldSnippets.class, "holderInitAndPutStaticFieldBooleanSnippet"));
        loadFieldLowering.setSnippet(Kind.Byte, snippet(FieldSnippets.class, "getFieldByteSnippet"));
        storeFieldLowering.setSnippet(Kind.Byte, snippet(FieldSnippets.class, "putFieldByteSnippet"));
        loadUnresolvedFieldLowering.setSnippet(Kind.Byte, snippet(FieldSnippets.class, "resolveAndGetInstanceFieldByteSnippet"));
        loadUnresolvedFieldLowering.staticFieldLowering.setSnippet(Kind.Byte, snippet(FieldSnippets.class, "resolveAndGetStaticFieldByteSnippet"));
        storeUnresolvedFieldLowering.setSnippet(Kind.Byte, snippet(FieldSnippets.class, "resolveAndPutInstanceFieldByteSnippet"));
        storeUnresolvedFieldLowering.staticFieldLowering.setSnippet(Kind.Byte, snippet(FieldSnippets.class, "resolveAndPutStaticFieldByteSnippet"));
        loadUnresolvedFieldLowering.initHolderInstanceFieldLowering.setSnippet(Kind.Byte, snippet(FieldSnippets.class, "holderInitAndGetInstanceFieldByteSnippet"));
        loadUnresolvedFieldLowering.initHolderStaticFieldLowering.setSnippet(Kind.Byte, snippet(FieldSnippets.class, "holderInitAndGetStaticFieldByteSnippet"));
        storeUnresolvedFieldLowering.initHolderInstanceFieldLowering.setSnippet(Kind.Byte, snippet(FieldSnippets.class, "holderInitAndPutInstanceFieldByteSnippet"));
        storeUnresolvedFieldLowering.initHolderStaticFieldLowering.setSnippet(Kind.Byte, snippet(FieldSnippets.class, "holderInitAndPutStaticFieldByteSnippet"));
        loadFieldLowering.setSnippet(Kind.Short, snippet(FieldSnippets.class, "getFieldShortSnippet"));
        storeFieldLowering.setSnippet(Kind.Short, snippet(FieldSnippets.class, "putFieldShortSnippet"));
        loadUnresolvedFieldLowering.setSnippet(Kind.Short, snippet(FieldSnippets.class, "resolveAndGetInstanceFieldShortSnippet"));
        loadUnresolvedFieldLowering.staticFieldLowering.setSnippet(Kind.Short, snippet(FieldSnippets.class, "resolveAndGetStaticFieldShortSnippet"));
        storeUnresolvedFieldLowering.setSnippet(Kind.Short, snippet(FieldSnippets.class, "resolveAndPutInstanceFieldShortSnippet"));
        storeUnresolvedFieldLowering.staticFieldLowering.setSnippet(Kind.Short, snippet(FieldSnippets.class, "resolveAndPutStaticFieldShortSnippet"));
        loadUnresolvedFieldLowering.initHolderInstanceFieldLowering.setSnippet(Kind.Short, snippet(FieldSnippets.class, "holderInitAndGetInstanceFieldShortSnippet"));
        loadUnresolvedFieldLowering.initHolderStaticFieldLowering.setSnippet(Kind.Short, snippet(FieldSnippets.class, "holderInitAndGetStaticFieldShortSnippet"));
        storeUnresolvedFieldLowering.initHolderInstanceFieldLowering.setSnippet(Kind.Short, snippet(FieldSnippets.class, "holderInitAndPutInstanceFieldShortSnippet"));
        storeUnresolvedFieldLowering.initHolderStaticFieldLowering.setSnippet(Kind.Short, snippet(FieldSnippets.class, "holderInitAndPutStaticFieldShortSnippet"));
        loadFieldLowering.setSnippet(Kind.Char, snippet(FieldSnippets.class, "getFieldCharSnippet"));
        storeFieldLowering.setSnippet(Kind.Char, snippet(FieldSnippets.class, "putFieldCharSnippet"));
        loadUnresolvedFieldLowering.setSnippet(Kind.Char, snippet(FieldSnippets.class, "resolveAndGetInstanceFieldCharSnippet"));
        loadUnresolvedFieldLowering.staticFieldLowering.setSnippet(Kind.Char, snippet(FieldSnippets.class, "resolveAndGetStaticFieldCharSnippet"));
        storeUnresolvedFieldLowering.setSnippet(Kind.Char, snippet(FieldSnippets.class, "resolveAndPutInstanceFieldCharSnippet"));
        storeUnresolvedFieldLowering.staticFieldLowering.setSnippet(Kind.Char, snippet(FieldSnippets.class, "resolveAndPutStaticFieldCharSnippet"));
        loadUnresolvedFieldLowering.initHolderInstanceFieldLowering.setSnippet(Kind.Char, snippet(FieldSnippets.class, "holderInitAndGetInstanceFieldCharSnippet"));
        loadUnresolvedFieldLowering.initHolderStaticFieldLowering.setSnippet(Kind.Char, snippet(FieldSnippets.class, "holderInitAndGetStaticFieldCharSnippet"));
        storeUnresolvedFieldLowering.initHolderInstanceFieldLowering.setSnippet(Kind.Char, snippet(FieldSnippets.class, "holderInitAndPutInstanceFieldCharSnippet"));
        storeUnresolvedFieldLowering.initHolderStaticFieldLowering.setSnippet(Kind.Char, snippet(FieldSnippets.class, "holderInitAndPutStaticFieldCharSnippet"));
        loadFieldLowering.setSnippet(Kind.Int, snippet(FieldSnippets.class, "getFieldIntSnippet"));
        storeFieldLowering.setSnippet(Kind.Int, snippet(FieldSnippets.class, "putFieldIntSnippet"));
        loadUnresolvedFieldLowering.setSnippet(Kind.Int, snippet(FieldSnippets.class, "resolveAndGetInstanceFieldIntSnippet"));
        loadUnresolvedFieldLowering.staticFieldLowering.setSnippet(Kind.Int, snippet(FieldSnippets.class, "resolveAndGetStaticFieldIntSnippet"));
        storeUnresolvedFieldLowering.setSnippet(Kind.Int, snippet(FieldSnippets.class, "resolveAndPutInstanceFieldIntSnippet"));
        storeUnresolvedFieldLowering.staticFieldLowering.setSnippet(Kind.Int, snippet(FieldSnippets.class, "resolveAndPutStaticFieldIntSnippet"));
        loadUnresolvedFieldLowering.initHolderInstanceFieldLowering.setSnippet(Kind.Int, snippet(FieldSnippets.class, "holderInitAndGetInstanceFieldIntSnippet"));
        loadUnresolvedFieldLowering.initHolderStaticFieldLowering.setSnippet(Kind.Int, snippet(FieldSnippets.class, "holderInitAndGetStaticFieldIntSnippet"));
        storeUnresolvedFieldLowering.initHolderInstanceFieldLowering.setSnippet(Kind.Int, snippet(FieldSnippets.class, "holderInitAndPutInstanceFieldIntSnippet"));
        storeUnresolvedFieldLowering.initHolderStaticFieldLowering.setSnippet(Kind.Int, snippet(FieldSnippets.class, "holderInitAndPutStaticFieldIntSnippet"));
        loadFieldLowering.setSnippet(Kind.Float, snippet(FieldSnippets.class, "getFieldFloatSnippet"));
        storeFieldLowering.setSnippet(Kind.Float, snippet(FieldSnippets.class, "putFieldFloatSnippet"));
        loadUnresolvedFieldLowering.setSnippet(Kind.Float, snippet(FieldSnippets.class, "resolveAndGetInstanceFieldFloatSnippet"));
        loadUnresolvedFieldLowering.staticFieldLowering.setSnippet(Kind.Float, snippet(FieldSnippets.class, "resolveAndGetStaticFieldFloatSnippet"));
        storeUnresolvedFieldLowering.setSnippet(Kind.Float, snippet(FieldSnippets.class, "resolveAndPutInstanceFieldFloatSnippet"));
        storeUnresolvedFieldLowering.staticFieldLowering.setSnippet(Kind.Float, snippet(FieldSnippets.class, "resolveAndPutStaticFieldFloatSnippet"));
        loadUnresolvedFieldLowering.initHolderInstanceFieldLowering.setSnippet(Kind.Float, snippet(FieldSnippets.class, "holderInitAndGetInstanceFieldFloatSnippet"));
        loadUnresolvedFieldLowering.initHolderStaticFieldLowering.setSnippet(Kind.Float, snippet(FieldSnippets.class, "holderInitAndGetStaticFieldFloatSnippet"));
        storeUnresolvedFieldLowering.initHolderInstanceFieldLowering.setSnippet(Kind.Float, snippet(FieldSnippets.class, "holderInitAndPutInstanceFieldFloatSnippet"));
        storeUnresolvedFieldLowering.initHolderStaticFieldLowering.setSnippet(Kind.Float, snippet(FieldSnippets.class, "holderInitAndPutStaticFieldFloatSnippet"));
        loadFieldLowering.setSnippet(Kind.Long, snippet(FieldSnippets.class, "getFieldLongSnippet"));
        storeFieldLowering.setSnippet(Kind.Long, snippet(FieldSnippets.class, "putFieldLongSnippet"));
        loadUnresolvedFieldLowering.setSnippet(Kind.Long, snippet(FieldSnippets.class, "resolveAndGetInstanceFieldLongSnippet"));
        loadUnresolvedFieldLowering.staticFieldLowering.setSnippet(Kind.Long, snippet(FieldSnippets.class, "resolveAndGetStaticFieldLongSnippet"));
        storeUnresolvedFieldLowering.setSnippet(Kind.Long, snippet(FieldSnippets.class, "resolveAndPutInstanceFieldLongSnippet"));
        storeUnresolvedFieldLowering.staticFieldLowering.setSnippet(Kind.Long, snippet(FieldSnippets.class, "resolveAndPutStaticFieldLongSnippet"));
        loadUnresolvedFieldLowering.initHolderInstanceFieldLowering.setSnippet(Kind.Long, snippet(FieldSnippets.class, "holderInitAndGetInstanceFieldLongSnippet"));
        loadUnresolvedFieldLowering.initHolderStaticFieldLowering.setSnippet(Kind.Long, snippet(FieldSnippets.class, "holderInitAndGetStaticFieldLongSnippet"));
        storeUnresolvedFieldLowering.initHolderInstanceFieldLowering.setSnippet(Kind.Long, snippet(FieldSnippets.class, "holderInitAndPutInstanceFieldLongSnippet"));
        storeUnresolvedFieldLowering.initHolderStaticFieldLowering.setSnippet(Kind.Long, snippet(FieldSnippets.class, "holderInitAndPutStaticFieldLongSnippet"));
        loadFieldLowering.setSnippet(Kind.Double, snippet(FieldSnippets.class, "getFieldDoubleSnippet"));
        storeFieldLowering.setSnippet(Kind.Double, snippet(FieldSnippets.class, "putFieldDoubleSnippet"));
        loadUnresolvedFieldLowering.setSnippet(Kind.Double, snippet(FieldSnippets.class, "resolveAndGetInstanceFieldDoubleSnippet"));
        loadUnresolvedFieldLowering.staticFieldLowering.setSnippet(Kind.Double, snippet(FieldSnippets.class, "resolveAndGetStaticFieldDoubleSnippet"));
        storeUnresolvedFieldLowering.setSnippet(Kind.Double, snippet(FieldSnippets.class, "resolveAndPutInstanceFieldDoubleSnippet"));
        storeUnresolvedFieldLowering.staticFieldLowering.setSnippet(Kind.Double, snippet(FieldSnippets.class, "resolveAndPutStaticFieldDoubleSnippet"));
        loadUnresolvedFieldLowering.initHolderInstanceFieldLowering.setSnippet(Kind.Double, snippet(FieldSnippets.class, "holderInitAndGetInstanceFieldDoubleSnippet"));
        loadUnresolvedFieldLowering.initHolderStaticFieldLowering.setSnippet(Kind.Double, snippet(FieldSnippets.class, "holderInitAndGetStaticFieldDoubleSnippet"));
        storeUnresolvedFieldLowering.initHolderInstanceFieldLowering.setSnippet(Kind.Double, snippet(FieldSnippets.class, "holderInitAndPutInstanceFieldDoubleSnippet"));
        storeUnresolvedFieldLowering.initHolderStaticFieldLowering.setSnippet(Kind.Double, snippet(FieldSnippets.class, "holderInitAndPutStaticFieldDoubleSnippet"));
        loadFieldLowering.setSnippet(Kind.Object, snippet(FieldSnippets.class, "getFieldObjectSnippet"));
        storeFieldLowering.setSnippet(Kind.Object, snippet(FieldSnippets.class, "putFieldObjectSnippet"));
        loadUnresolvedFieldLowering.setSnippet(Kind.Object, snippet(FieldSnippets.class, "resolveAndGetInstanceFieldObjectSnippet"));
        loadUnresolvedFieldLowering.staticFieldLowering.setSnippet(Kind.Object, snippet(FieldSnippets.class, "resolveAndGetStaticFieldObjectSnippet"));
        storeUnresolvedFieldLowering.setSnippet(Kind.Object, snippet(FieldSnippets.class, "resolveAndPutInstanceFieldObjectSnippet"));
        storeUnresolvedFieldLowering.staticFieldLowering.setSnippet(Kind.Object, snippet(FieldSnippets.class, "resolveAndPutStaticFieldObjectSnippet"));
        loadUnresolvedFieldLowering.initHolderInstanceFieldLowering.setSnippet(Kind.Object, snippet(FieldSnippets.class, "holderInitAndGetInstanceFieldObjectSnippet"));
        loadUnresolvedFieldLowering.initHolderStaticFieldLowering.setSnippet(Kind.Object, snippet(FieldSnippets.class, "holderInitAndGetStaticFieldObjectSnippet"));
        storeUnresolvedFieldLowering.initHolderInstanceFieldLowering.setSnippet(Kind.Object, snippet(FieldSnippets.class, "holderInitAndPutInstanceFieldObjectSnippet"));
        storeUnresolvedFieldLowering.initHolderStaticFieldLowering.setSnippet(Kind.Object, snippet(FieldSnippets.class, "holderInitAndPutStaticFieldObjectSnippet"));
    }
// END GENERATED CODE

}
