/*
 * Copyright (c) 2011, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */
package com.oracle.max.vm.ext.vma;

import com.sun.cri.bytecode.*;

/**
 * Bytecodes defined as enum with useful supporting methods for automatic generation.
 */
public enum VMABytecodes {

    // BEGIN GENERATED CODE

    NOP(Bytecodes.NOP, "Bytecode"),
    ACONST_NULL(Bytecodes.ACONST_NULL, "ConstLoad"),
    ICONST_M1(Bytecodes.ICONST_M1, "ConstLoad"),
    ICONST_0(Bytecodes.ICONST_0, "ConstLoad"),
    ICONST_1(Bytecodes.ICONST_1, "ConstLoad"),
    ICONST_2(Bytecodes.ICONST_2, "ConstLoad"),
    ICONST_3(Bytecodes.ICONST_3, "ConstLoad"),
    ICONST_4(Bytecodes.ICONST_4, "ConstLoad"),
    ICONST_5(Bytecodes.ICONST_5, "ConstLoad"),
    LCONST_0(Bytecodes.LCONST_0, "ConstLoad"),
    LCONST_1(Bytecodes.LCONST_1, "ConstLoad"),
    FCONST_0(Bytecodes.FCONST_0, "ConstLoad"),
    FCONST_1(Bytecodes.FCONST_1, "ConstLoad"),
    FCONST_2(Bytecodes.FCONST_2, "ConstLoad"),
    DCONST_0(Bytecodes.DCONST_0, "ConstLoad"),
    DCONST_1(Bytecodes.DCONST_1, "ConstLoad"),
    BIPUSH(Bytecodes.BIPUSH, "IPush"),
    SIPUSH(Bytecodes.SIPUSH, "IPush"),
    LDC(Bytecodes.LDC, "ConstLoad"),
    LDC_W(Bytecodes.LDC_W, "ConstLoad"),
    LDC2_W(Bytecodes.LDC2_W, "ConstLoad"),
    ILOAD(Bytecodes.ILOAD, "Load"),
    LLOAD(Bytecodes.LLOAD, "Load"),
    FLOAD(Bytecodes.FLOAD, "Load"),
    DLOAD(Bytecodes.DLOAD, "Load"),
    ALOAD(Bytecodes.ALOAD, "Load"),
    ILOAD_0(Bytecodes.ILOAD_0, "Load"),
    ILOAD_1(Bytecodes.ILOAD_1, "Load"),
    ILOAD_2(Bytecodes.ILOAD_2, "Load"),
    ILOAD_3(Bytecodes.ILOAD_3, "Load"),
    LLOAD_0(Bytecodes.LLOAD_0, "Load"),
    LLOAD_1(Bytecodes.LLOAD_1, "Load"),
    LLOAD_2(Bytecodes.LLOAD_2, "Load"),
    LLOAD_3(Bytecodes.LLOAD_3, "Load"),
    FLOAD_0(Bytecodes.FLOAD_0, "Load"),
    FLOAD_1(Bytecodes.FLOAD_1, "Load"),
    FLOAD_2(Bytecodes.FLOAD_2, "Load"),
    FLOAD_3(Bytecodes.FLOAD_3, "Load"),
    DLOAD_0(Bytecodes.DLOAD_0, "Load"),
    DLOAD_1(Bytecodes.DLOAD_1, "Load"),
    DLOAD_2(Bytecodes.DLOAD_2, "Load"),
    DLOAD_3(Bytecodes.DLOAD_3, "Load"),
    ALOAD_0(Bytecodes.ALOAD_0, "Load"),
    ALOAD_1(Bytecodes.ALOAD_1, "Load"),
    ALOAD_2(Bytecodes.ALOAD_2, "Load"),
    ALOAD_3(Bytecodes.ALOAD_3, "Load"),
    IALOAD(Bytecodes.IALOAD, "ArrayLoad"),
    LALOAD(Bytecodes.LALOAD, "ArrayLoad"),
    FALOAD(Bytecodes.FALOAD, "ArrayLoad"),
    DALOAD(Bytecodes.DALOAD, "ArrayLoad"),
    AALOAD(Bytecodes.AALOAD, "ArrayLoad"),
    BALOAD(Bytecodes.BALOAD, "ArrayLoad"),
    CALOAD(Bytecodes.CALOAD, "ArrayLoad"),
    SALOAD(Bytecodes.SALOAD, "ArrayLoad"),
    ISTORE(Bytecodes.ISTORE, "Store"),
    LSTORE(Bytecodes.LSTORE, "Store"),
    FSTORE(Bytecodes.FSTORE, "Store"),
    DSTORE(Bytecodes.DSTORE, "Store"),
    ASTORE(Bytecodes.ASTORE, "Store"),
    ISTORE_0(Bytecodes.ISTORE_0, "Store"),
    ISTORE_1(Bytecodes.ISTORE_1, "Store"),
    ISTORE_2(Bytecodes.ISTORE_2, "Store"),
    ISTORE_3(Bytecodes.ISTORE_3, "Store"),
    LSTORE_0(Bytecodes.LSTORE_0, "Store"),
    LSTORE_1(Bytecodes.LSTORE_1, "Store"),
    LSTORE_2(Bytecodes.LSTORE_2, "Store"),
    LSTORE_3(Bytecodes.LSTORE_3, "Store"),
    FSTORE_0(Bytecodes.FSTORE_0, "Store"),
    FSTORE_1(Bytecodes.FSTORE_1, "Store"),
    FSTORE_2(Bytecodes.FSTORE_2, "Store"),
    FSTORE_3(Bytecodes.FSTORE_3, "Store"),
    DSTORE_0(Bytecodes.DSTORE_0, "Store"),
    DSTORE_1(Bytecodes.DSTORE_1, "Store"),
    DSTORE_2(Bytecodes.DSTORE_2, "Store"),
    DSTORE_3(Bytecodes.DSTORE_3, "Store"),
    ASTORE_0(Bytecodes.ASTORE_0, "Store"),
    ASTORE_1(Bytecodes.ASTORE_1, "Store"),
    ASTORE_2(Bytecodes.ASTORE_2, "Store"),
    ASTORE_3(Bytecodes.ASTORE_3, "Store"),
    IASTORE(Bytecodes.IASTORE, "ArrayStore"),
    LASTORE(Bytecodes.LASTORE, "ArrayStore"),
    FASTORE(Bytecodes.FASTORE, "ArrayStore"),
    DASTORE(Bytecodes.DASTORE, "ArrayStore"),
    AASTORE(Bytecodes.AASTORE, "ArrayStore"),
    BASTORE(Bytecodes.BASTORE, "ArrayStore"),
    CASTORE(Bytecodes.CASTORE, "ArrayStore"),
    SASTORE(Bytecodes.SASTORE, "ArrayStore"),
    POP(Bytecodes.POP, "StackAdjust"),
    POP2(Bytecodes.POP2, "StackAdjust"),
    DUP(Bytecodes.DUP, "StackAdjust"),
    DUP_X1(Bytecodes.DUP_X1, "StackAdjust"),
    DUP_X2(Bytecodes.DUP_X2, "StackAdjust"),
    DUP2(Bytecodes.DUP2, "StackAdjust"),
    DUP2_X1(Bytecodes.DUP2_X1, "StackAdjust"),
    DUP2_X2(Bytecodes.DUP2_X2, "StackAdjust"),
    SWAP(Bytecodes.SWAP, "StackAdjust"),
    IADD(Bytecodes.IADD, "Operation"),
    LADD(Bytecodes.LADD, "Operation"),
    FADD(Bytecodes.FADD, "Operation"),
    DADD(Bytecodes.DADD, "Operation"),
    ISUB(Bytecodes.ISUB, "Operation"),
    LSUB(Bytecodes.LSUB, "Operation"),
    FSUB(Bytecodes.FSUB, "Operation"),
    DSUB(Bytecodes.DSUB, "Operation"),
    IMUL(Bytecodes.IMUL, "Operation"),
    LMUL(Bytecodes.LMUL, "Operation"),
    FMUL(Bytecodes.FMUL, "Operation"),
    DMUL(Bytecodes.DMUL, "Operation"),
    IDIV(Bytecodes.IDIV, "Operation"),
    LDIV(Bytecodes.LDIV, "Operation"),
    FDIV(Bytecodes.FDIV, "Operation"),
    DDIV(Bytecodes.DDIV, "Operation"),
    IREM(Bytecodes.IREM, "Operation"),
    LREM(Bytecodes.LREM, "Operation"),
    FREM(Bytecodes.FREM, "Operation"),
    DREM(Bytecodes.DREM, "Operation"),
    INEG(Bytecodes.INEG, "Operation"),
    LNEG(Bytecodes.LNEG, "Operation"),
    FNEG(Bytecodes.FNEG, "Operation"),
    DNEG(Bytecodes.DNEG, "Operation"),
    ISHL(Bytecodes.ISHL, "Operation"),
    LSHL(Bytecodes.LSHL, "Operation"),
    ISHR(Bytecodes.ISHR, "Operation"),
    LSHR(Bytecodes.LSHR, "Operation"),
    IUSHR(Bytecodes.IUSHR, "Operation"),
    LUSHR(Bytecodes.LUSHR, "Operation"),
    IAND(Bytecodes.IAND, "Operation"),
    LAND(Bytecodes.LAND, "Operation"),
    IOR(Bytecodes.IOR, "Operation"),
    LOR(Bytecodes.LOR, "Operation"),
    IXOR(Bytecodes.IXOR, "Operation"),
    LXOR(Bytecodes.LXOR, "Operation"),
    IINC(Bytecodes.IINC, "IInc"),
    I2L(Bytecodes.I2L, "Conversion"),
    I2F(Bytecodes.I2F, "Conversion"),
    I2D(Bytecodes.I2D, "Conversion"),
    L2I(Bytecodes.L2I, "Conversion"),
    L2F(Bytecodes.L2F, "Conversion"),
    L2D(Bytecodes.L2D, "Conversion"),
    F2I(Bytecodes.F2I, "Conversion"),
    F2L(Bytecodes.F2L, "Conversion"),
    F2D(Bytecodes.F2D, "Conversion"),
    D2I(Bytecodes.D2I, "Conversion"),
    D2L(Bytecodes.D2L, "Conversion"),
    D2F(Bytecodes.D2F, "Conversion"),
    I2B(Bytecodes.I2B, "Conversion"),
    I2C(Bytecodes.I2C, "Conversion"),
    I2S(Bytecodes.I2S, "Conversion"),
    LCMP(Bytecodes.LCMP, "Operation"),
    FCMPL(Bytecodes.FCMPL, "Operation"),
    FCMPG(Bytecodes.FCMPG, "Operation"),
    DCMPL(Bytecodes.DCMPL, "Operation"),
    DCMPG(Bytecodes.DCMPG, "Operation"),
    IFEQ(Bytecodes.IFEQ, "If"),
    IFNE(Bytecodes.IFNE, "If"),
    IFLT(Bytecodes.IFLT, "If"),
    IFGE(Bytecodes.IFGE, "If"),
    IFGT(Bytecodes.IFGT, "If"),
    IFLE(Bytecodes.IFLE, "If"),
    IF_ICMPEQ(Bytecodes.IF_ICMPEQ, "If"),
    IF_ICMPNE(Bytecodes.IF_ICMPNE, "If"),
    IF_ICMPLT(Bytecodes.IF_ICMPLT, "If"),
    IF_ICMPGE(Bytecodes.IF_ICMPGE, "If"),
    IF_ICMPGT(Bytecodes.IF_ICMPGT, "If"),
    IF_ICMPLE(Bytecodes.IF_ICMPLE, "If"),
    IF_ACMPEQ(Bytecodes.IF_ACMPEQ, "If"),
    IF_ACMPNE(Bytecodes.IF_ACMPNE, "If"),
    GOTO(Bytecodes.GOTO, "Bytecode"),
    JSR(Bytecodes.JSR, "Bytecode"),
    RET(Bytecodes.RET, "Bytecode"),
    TABLESWITCH(Bytecodes.TABLESWITCH, "Bytecode"),
    LOOKUPSWITCH(Bytecodes.LOOKUPSWITCH, "Bytecode"),
    IRETURN(Bytecodes.IRETURN, "Return"),
    LRETURN(Bytecodes.LRETURN, "Return"),
    FRETURN(Bytecodes.FRETURN, "Return"),
    DRETURN(Bytecodes.DRETURN, "Return"),
    ARETURN(Bytecodes.ARETURN, "Return"),
    RETURN(Bytecodes.RETURN, "Return"),
    GETSTATIC(Bytecodes.GETSTATIC, "GetStatic"),
    PUTSTATIC(Bytecodes.PUTSTATIC, "PutStatic"),
    GETFIELD(Bytecodes.GETFIELD, "GetField"),
    PUTFIELD(Bytecodes.PUTFIELD, "PutField"),
    INVOKEVIRTUAL(Bytecodes.INVOKEVIRTUAL, "InvokeVirtual"),
    INVOKESPECIAL(Bytecodes.INVOKESPECIAL, "InvokeSpecial"),
    INVOKESTATIC(Bytecodes.INVOKESTATIC, "InvokeStatic"),
    INVOKEINTERFACE(Bytecodes.INVOKEINTERFACE, "InvokeInterface"),
    XXXUNUSEDXXX(Bytecodes.XXXUNUSEDXXX, "Bytecode"),
    NEW(Bytecodes.NEW, "New"),
    NEWARRAY(Bytecodes.NEWARRAY, "NewArray"),
    ANEWARRAY(Bytecodes.ANEWARRAY, "NewArray"),
    ARRAYLENGTH(Bytecodes.ARRAYLENGTH, "ArrayLength"),
    ATHROW(Bytecodes.ATHROW, "Throw"),
    CHECKCAST(Bytecodes.CHECKCAST, "CheckCast"),
    INSTANCEOF(Bytecodes.INSTANCEOF, "InstanceOf"),
    MONITORENTER(Bytecodes.MONITORENTER, "MonitorEnter"),
    MONITOREXIT(Bytecodes.MONITOREXIT, "MonitorExit"),
    WIDE(Bytecodes.WIDE, "Bytecode"),
    MULTIANEWARRAY(Bytecodes.MULTIANEWARRAY, "MultiNewArray"),
    IFNULL(Bytecodes.IFNULL, "If"),
    IFNONNULL(Bytecodes.IFNONNULL, "If"),
    GOTO_W(Bytecodes.GOTO_W, "Bytecode"),
    JSR_W(Bytecodes.JSR_W, "Bytecode"),
    BREAKPOINT(Bytecodes.BREAKPOINT, "Bytecode"),
    JNICALL(Bytecodes.JNICALL, "Bytecode"),
    JNIOP(Bytecodes.JNIOP, "Bytecode"),
    TEMPLATE_CALL(Bytecodes.TEMPLATE_CALL, "Bytecode"),
    WLOAD(Bytecodes.WLOAD, "Load"),
    WLOAD_0(Bytecodes.WLOAD_0, "Load"),
    WLOAD_1(Bytecodes.WLOAD_1, "Load"),
    WLOAD_2(Bytecodes.WLOAD_2, "Load"),
    WLOAD_3(Bytecodes.WLOAD_3, "Load"),
    WSTORE(Bytecodes.WSTORE, "Store"),
    WSTORE_0(Bytecodes.WSTORE_0, "Store"),
    WSTORE_1(Bytecodes.WSTORE_1, "Store"),
    WSTORE_2(Bytecodes.WSTORE_2, "Store"),
    WSTORE_3(Bytecodes.WSTORE_3, "Store"),
    WCONST_0(Bytecodes.WCONST_0, "ConstLoad"),
    WDIV(Bytecodes.WDIV, "Operation"),
    WDIVI(Bytecodes.WDIVI, "Operation"),
    WREM(Bytecodes.WREM, "Operation"),
    WREMI(Bytecodes.WREMI, "Operation"),
    ICMP(Bytecodes.ICMP, "Bytecode"),
    WCMP(Bytecodes.WCMP, "Bytecode"),
    PREAD(Bytecodes.PREAD, "Bytecode"),
    PWRITE(Bytecodes.PWRITE, "Bytecode"),
    PGET(Bytecodes.PGET, "Bytecode"),
    PSET(Bytecodes.PSET, "Bytecode"),
    PCMPSWP(Bytecodes.PCMPSWP, "Bytecode"),
    MOV_I2F(Bytecodes.MOV_I2F, "Conversion"),
    MOV_F2I(Bytecodes.MOV_F2I, "Conversion"),
    MOV_L2D(Bytecodes.MOV_L2D, "Conversion"),
    MOV_D2L(Bytecodes.MOV_D2L, "Conversion"),
    UCMP(Bytecodes.UCMP, "Bytecode"),
    UWCMP(Bytecodes.UWCMP, "Bytecode"),
    READREG(Bytecodes.READREG, "Bytecode"),
    WRITEREG(Bytecodes.WRITEREG, "Bytecode"),
    INCREG(Bytecodes.INCREG, "Bytecode"),
    UNSAFE_CAST(Bytecodes.UNSAFE_CAST, "Bytecode"),
    WRETURN(Bytecodes.WRETURN, "Return"),
    INFOPOINT(Bytecodes.INFOPOINT, "Bytecode"),
    SAFEPOINT(Bytecodes.SAFEPOINT, "Bytecode"),
    HERE(Bytecodes.HERE, "Bytecode"),
    INFO(Bytecodes.INFO, "Bytecode"),
    ALLOCA(Bytecodes.ALLOCA, "Bytecode"),
    MEMBAR(Bytecodes.MEMBAR, "Bytecode"),
    STACKHANDLE(Bytecodes.STACKHANDLE, "Bytecode"),
    PAUSE(Bytecodes.PAUSE, "Bytecode"),
    BREAKPOINT_TRAP(Bytecodes.BREAKPOINT_TRAP, "Bytecode"),
    ADD_SP(Bytecodes.ADD_SP, "Bytecode"),
    FLUSHW(Bytecodes.FLUSHW, "Bytecode"),
    LSB(Bytecodes.LSB, "Bytecode"),
    MSB(Bytecodes.MSB, "Bytecode"),
    PCMPSWP_INT(Bytecodes.PCMPSWP_INT, "Bytecode"),
    PCMPSWP_LONG(Bytecodes.PCMPSWP_LONG, "Bytecode"),
    PCMPSWP_WORD(Bytecodes.PCMPSWP_WORD, "Bytecode"),
    PCMPSWP_REFERENCE(Bytecodes.PCMPSWP_REFERENCE, "Bytecode"),
    PCMPSWP_INT_I(Bytecodes.PCMPSWP_INT_I, "Bytecode"),
    PCMPSWP_LONG_I(Bytecodes.PCMPSWP_LONG_I, "Bytecode"),
    PCMPSWP_WORD_I(Bytecodes.PCMPSWP_WORD_I, "Bytecode"),
    PCMPSWP_REFERENCE_I(Bytecodes.PCMPSWP_REFERENCE_I, "Bytecode"),
    PREAD_BYTE(Bytecodes.PREAD_BYTE, "Bytecode"),
    PREAD_CHAR(Bytecodes.PREAD_CHAR, "Bytecode"),
    PREAD_SHORT(Bytecodes.PREAD_SHORT, "Bytecode"),
    PREAD_INT(Bytecodes.PREAD_INT, "Bytecode"),
    PREAD_FLOAT(Bytecodes.PREAD_FLOAT, "Bytecode"),
    PREAD_LONG(Bytecodes.PREAD_LONG, "Bytecode"),
    PREAD_DOUBLE(Bytecodes.PREAD_DOUBLE, "Bytecode"),
    PREAD_WORD(Bytecodes.PREAD_WORD, "Bytecode"),
    PREAD_REFERENCE(Bytecodes.PREAD_REFERENCE, "Bytecode"),
    PREAD_BYTE_I(Bytecodes.PREAD_BYTE_I, "Bytecode"),
    PREAD_CHAR_I(Bytecodes.PREAD_CHAR_I, "Bytecode"),
    PREAD_SHORT_I(Bytecodes.PREAD_SHORT_I, "Bytecode"),
    PREAD_INT_I(Bytecodes.PREAD_INT_I, "Bytecode"),
    PREAD_FLOAT_I(Bytecodes.PREAD_FLOAT_I, "Bytecode"),
    PREAD_LONG_I(Bytecodes.PREAD_LONG_I, "Bytecode"),
    PREAD_DOUBLE_I(Bytecodes.PREAD_DOUBLE_I, "Bytecode"),
    PREAD_WORD_I(Bytecodes.PREAD_WORD_I, "Bytecode"),
    PREAD_REFERENCE_I(Bytecodes.PREAD_REFERENCE_I, "Bytecode"),
    PWRITE_BYTE(Bytecodes.PWRITE_BYTE, "Bytecode"),
    PWRITE_SHORT(Bytecodes.PWRITE_SHORT, "Bytecode"),
    PWRITE_INT(Bytecodes.PWRITE_INT, "Bytecode"),
    PWRITE_FLOAT(Bytecodes.PWRITE_FLOAT, "Bytecode"),
    PWRITE_LONG(Bytecodes.PWRITE_LONG, "Bytecode"),
    PWRITE_DOUBLE(Bytecodes.PWRITE_DOUBLE, "Bytecode"),
    PWRITE_WORD(Bytecodes.PWRITE_WORD, "Bytecode"),
    PWRITE_REFERENCE(Bytecodes.PWRITE_REFERENCE, "Bytecode"),
    PWRITE_BYTE_I(Bytecodes.PWRITE_BYTE_I, "Bytecode"),
    PWRITE_SHORT_I(Bytecodes.PWRITE_SHORT_I, "Bytecode"),
    PWRITE_INT_I(Bytecodes.PWRITE_INT_I, "Bytecode"),
    PWRITE_FLOAT_I(Bytecodes.PWRITE_FLOAT_I, "Bytecode"),
    PWRITE_LONG_I(Bytecodes.PWRITE_LONG_I, "Bytecode"),
    PWRITE_DOUBLE_I(Bytecodes.PWRITE_DOUBLE_I, "Bytecode"),
    PWRITE_WORD_I(Bytecodes.PWRITE_WORD_I, "Bytecode"),
    PWRITE_REFERENCE_I(Bytecodes.PWRITE_REFERENCE_I, "Bytecode"),
    PGET_BYTE(Bytecodes.PGET_BYTE, "Bytecode"),
    PGET_CHAR(Bytecodes.PGET_CHAR, "Bytecode"),
    PGET_SHORT(Bytecodes.PGET_SHORT, "Bytecode"),
    PGET_INT(Bytecodes.PGET_INT, "Bytecode"),
    PGET_FLOAT(Bytecodes.PGET_FLOAT, "Bytecode"),
    PGET_LONG(Bytecodes.PGET_LONG, "Bytecode"),
    PGET_DOUBLE(Bytecodes.PGET_DOUBLE, "Bytecode"),
    PGET_WORD(Bytecodes.PGET_WORD, "Bytecode"),
    PGET_REFERENCE(Bytecodes.PGET_REFERENCE, "Bytecode"),
    PSET_BYTE(Bytecodes.PSET_BYTE, "Bytecode"),
    PSET_SHORT(Bytecodes.PSET_SHORT, "Bytecode"),
    PSET_INT(Bytecodes.PSET_INT, "Bytecode"),
    PSET_FLOAT(Bytecodes.PSET_FLOAT, "Bytecode"),
    PSET_LONG(Bytecodes.PSET_LONG, "Bytecode"),
    PSET_DOUBLE(Bytecodes.PSET_DOUBLE, "Bytecode"),
    PSET_WORD(Bytecodes.PSET_WORD, "Bytecode"),
    PSET_REFERENCE(Bytecodes.PSET_REFERENCE, "Bytecode"),
    MEMBAR_LOAD_LOAD(Bytecodes.MEMBAR_LOAD_LOAD, "Bytecode"),
    MEMBAR_LOAD_STORE(Bytecodes.MEMBAR_LOAD_STORE, "Bytecode"),
    MEMBAR_STORE_LOAD(Bytecodes.MEMBAR_STORE_LOAD, "Bytecode"),
    MEMBAR_STORE_STORE(Bytecodes.MEMBAR_STORE_STORE, "Bytecode"),
    JNIOP_LINK(Bytecodes.JNIOP_LINK, "Bytecode"),
    JNIOP_J2N(Bytecodes.JNIOP_J2N, "Bytecode"),
    JNIOP_N2J(Bytecodes.JNIOP_N2J, "Bytecode"),
    ILLEGAL(Bytecodes.ILLEGAL, "Bytecode"),
    END(Bytecodes.END, "Bytecode"),
    LAST_JVM_OPCODE(Bytecodes.LAST_JVM_OPCODE, "Bytecode"),
    MENTRY(-1, "MethodEntry");

    // END GENERATED CODE

    public final int code;
    public final String methodName;

    private VMABytecodes(int code, String methodName) {
        this.code = code;
        this.methodName = methodName;
    }

    public static void main(String[] args) {
        for (VMABytecodes b : VMABytecodes.values()) {
            System.out.println(b + ", ord=" + b.ordinal() + ", code=" + b.code);
        }
    }

}
