/*
 * Copyright (c) 2011, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */
package com.oracle.max.vm.ext.vma;

import com.sun.cri.bytecode.*;

/**
 * Bytecodes defined as enum with useful supporting methods for automatic generation.
 */
public enum VMABytecodes {

    // BEGIN GENERATED CODE

    NOP(Bytecodes.NOP, "NOP"),
    ACONST_NULL(Bytecodes.ACONST_NULL, "ACONST_NULL"),
    ICONST_M1(Bytecodes.ICONST_M1, "ICONST_M1"),
    ICONST_0(Bytecodes.ICONST_0, "ICONST_0"),
    ICONST_1(Bytecodes.ICONST_1, "ICONST_1"),
    ICONST_2(Bytecodes.ICONST_2, "ICONST_2"),
    ICONST_3(Bytecodes.ICONST_3, "ICONST_3"),
    ICONST_4(Bytecodes.ICONST_4, "ICONST_4"),
    ICONST_5(Bytecodes.ICONST_5, "ICONST_5"),
    LCONST_0(Bytecodes.LCONST_0, "LCONST_0"),
    LCONST_1(Bytecodes.LCONST_1, "LCONST_1"),
    FCONST_0(Bytecodes.FCONST_0, "FCONST_0"),
    FCONST_1(Bytecodes.FCONST_1, "FCONST_1"),
    FCONST_2(Bytecodes.FCONST_2, "FCONST_2"),
    DCONST_0(Bytecodes.DCONST_0, "DCONST_0"),
    DCONST_1(Bytecodes.DCONST_1, "DCONST_1"),
    BIPUSH(Bytecodes.BIPUSH, "BIPUSH"),
    SIPUSH(Bytecodes.SIPUSH, "SIPUSH"),
    LDC(Bytecodes.LDC, "LDC"),
    LDC_W(Bytecodes.LDC_W, "LDC_W"),
    LDC2_W(Bytecodes.LDC2_W, "LDC2_W"),
    ILOAD(Bytecodes.ILOAD, "ILOAD"),
    LLOAD(Bytecodes.LLOAD, "LLOAD"),
    FLOAD(Bytecodes.FLOAD, "FLOAD"),
    DLOAD(Bytecodes.DLOAD, "DLOAD"),
    ALOAD(Bytecodes.ALOAD, "ALOAD"),
    ILOAD_0(Bytecodes.ILOAD_0, "ILOAD_0"),
    ILOAD_1(Bytecodes.ILOAD_1, "ILOAD_1"),
    ILOAD_2(Bytecodes.ILOAD_2, "ILOAD_2"),
    ILOAD_3(Bytecodes.ILOAD_3, "ILOAD_3"),
    LLOAD_0(Bytecodes.LLOAD_0, "LLOAD_0"),
    LLOAD_1(Bytecodes.LLOAD_1, "LLOAD_1"),
    LLOAD_2(Bytecodes.LLOAD_2, "LLOAD_2"),
    LLOAD_3(Bytecodes.LLOAD_3, "LLOAD_3"),
    FLOAD_0(Bytecodes.FLOAD_0, "FLOAD_0"),
    FLOAD_1(Bytecodes.FLOAD_1, "FLOAD_1"),
    FLOAD_2(Bytecodes.FLOAD_2, "FLOAD_2"),
    FLOAD_3(Bytecodes.FLOAD_3, "FLOAD_3"),
    DLOAD_0(Bytecodes.DLOAD_0, "DLOAD_0"),
    DLOAD_1(Bytecodes.DLOAD_1, "DLOAD_1"),
    DLOAD_2(Bytecodes.DLOAD_2, "DLOAD_2"),
    DLOAD_3(Bytecodes.DLOAD_3, "DLOAD_3"),
    ALOAD_0(Bytecodes.ALOAD_0, "ALOAD_0"),
    ALOAD_1(Bytecodes.ALOAD_1, "ALOAD_1"),
    ALOAD_2(Bytecodes.ALOAD_2, "ALOAD_2"),
    ALOAD_3(Bytecodes.ALOAD_3, "ALOAD_3"),
    IALOAD(Bytecodes.IALOAD, "ArrayLoad"),
    LALOAD(Bytecodes.LALOAD, "ArrayLoad"),
    FALOAD(Bytecodes.FALOAD, "ArrayLoad"),
    DALOAD(Bytecodes.DALOAD, "ArrayLoad"),
    AALOAD(Bytecodes.AALOAD, "ArrayLoad"),
    BALOAD(Bytecodes.BALOAD, "ArrayLoad"),
    CALOAD(Bytecodes.CALOAD, "ArrayLoad"),
    SALOAD(Bytecodes.SALOAD, "ArrayLoad"),
    ISTORE(Bytecodes.ISTORE, "ISTORE"),
    LSTORE(Bytecodes.LSTORE, "LSTORE"),
    FSTORE(Bytecodes.FSTORE, "FSTORE"),
    DSTORE(Bytecodes.DSTORE, "DSTORE"),
    ASTORE(Bytecodes.ASTORE, "ASTORE"),
    ISTORE_0(Bytecodes.ISTORE_0, "ISTORE_0"),
    ISTORE_1(Bytecodes.ISTORE_1, "ISTORE_1"),
    ISTORE_2(Bytecodes.ISTORE_2, "ISTORE_2"),
    ISTORE_3(Bytecodes.ISTORE_3, "ISTORE_3"),
    LSTORE_0(Bytecodes.LSTORE_0, "LSTORE_0"),
    LSTORE_1(Bytecodes.LSTORE_1, "LSTORE_1"),
    LSTORE_2(Bytecodes.LSTORE_2, "LSTORE_2"),
    LSTORE_3(Bytecodes.LSTORE_3, "LSTORE_3"),
    FSTORE_0(Bytecodes.FSTORE_0, "FSTORE_0"),
    FSTORE_1(Bytecodes.FSTORE_1, "FSTORE_1"),
    FSTORE_2(Bytecodes.FSTORE_2, "FSTORE_2"),
    FSTORE_3(Bytecodes.FSTORE_3, "FSTORE_3"),
    DSTORE_0(Bytecodes.DSTORE_0, "DSTORE_0"),
    DSTORE_1(Bytecodes.DSTORE_1, "DSTORE_1"),
    DSTORE_2(Bytecodes.DSTORE_2, "DSTORE_2"),
    DSTORE_3(Bytecodes.DSTORE_3, "DSTORE_3"),
    ASTORE_0(Bytecodes.ASTORE_0, "ASTORE_0"),
    ASTORE_1(Bytecodes.ASTORE_1, "ASTORE_1"),
    ASTORE_2(Bytecodes.ASTORE_2, "ASTORE_2"),
    ASTORE_3(Bytecodes.ASTORE_3, "ASTORE_3"),
    IASTORE(Bytecodes.IASTORE, "ArrayStore"),
    LASTORE(Bytecodes.LASTORE, "ArrayStore"),
    FASTORE(Bytecodes.FASTORE, "ArrayStore"),
    DASTORE(Bytecodes.DASTORE, "ArrayStore"),
    AASTORE(Bytecodes.AASTORE, "ArrayStore"),
    BASTORE(Bytecodes.BASTORE, "ArrayStore"),
    CASTORE(Bytecodes.CASTORE, "ArrayStore"),
    SASTORE(Bytecodes.SASTORE, "ArrayStore"),
    POP(Bytecodes.POP, "POP"),
    POP2(Bytecodes.POP2, "POP2"),
    DUP(Bytecodes.DUP, "DUP"),
    DUP_X1(Bytecodes.DUP_X1, "DUP_X1"),
    DUP_X2(Bytecodes.DUP_X2, "DUP_X2"),
    DUP2(Bytecodes.DUP2, "DUP2"),
    DUP2_X1(Bytecodes.DUP2_X1, "DUP2_X1"),
    DUP2_X2(Bytecodes.DUP2_X2, "DUP2_X2"),
    SWAP(Bytecodes.SWAP, "SWAP"),
    IADD(Bytecodes.IADD, "IADD"),
    LADD(Bytecodes.LADD, "LADD"),
    FADD(Bytecodes.FADD, "FADD"),
    DADD(Bytecodes.DADD, "DADD"),
    ISUB(Bytecodes.ISUB, "ISUB"),
    LSUB(Bytecodes.LSUB, "LSUB"),
    FSUB(Bytecodes.FSUB, "FSUB"),
    DSUB(Bytecodes.DSUB, "DSUB"),
    IMUL(Bytecodes.IMUL, "IMUL"),
    LMUL(Bytecodes.LMUL, "LMUL"),
    FMUL(Bytecodes.FMUL, "FMUL"),
    DMUL(Bytecodes.DMUL, "DMUL"),
    IDIV(Bytecodes.IDIV, "IDIV"),
    LDIV(Bytecodes.LDIV, "LDIV"),
    FDIV(Bytecodes.FDIV, "FDIV"),
    DDIV(Bytecodes.DDIV, "DDIV"),
    IREM(Bytecodes.IREM, "IREM"),
    LREM(Bytecodes.LREM, "LREM"),
    FREM(Bytecodes.FREM, "FREM"),
    DREM(Bytecodes.DREM, "DREM"),
    INEG(Bytecodes.INEG, "INEG"),
    LNEG(Bytecodes.LNEG, "LNEG"),
    FNEG(Bytecodes.FNEG, "FNEG"),
    DNEG(Bytecodes.DNEG, "DNEG"),
    ISHL(Bytecodes.ISHL, "ISHL"),
    LSHL(Bytecodes.LSHL, "LSHL"),
    ISHR(Bytecodes.ISHR, "ISHR"),
    LSHR(Bytecodes.LSHR, "LSHR"),
    IUSHR(Bytecodes.IUSHR, "IUSHR"),
    LUSHR(Bytecodes.LUSHR, "LUSHR"),
    IAND(Bytecodes.IAND, "IAND"),
    LAND(Bytecodes.LAND, "LAND"),
    IOR(Bytecodes.IOR, "IOR"),
    LOR(Bytecodes.LOR, "LOR"),
    IXOR(Bytecodes.IXOR, "IXOR"),
    LXOR(Bytecodes.LXOR, "LXOR"),
    IINC(Bytecodes.IINC, "IINC"),
    I2L(Bytecodes.I2L, "I2L"),
    I2F(Bytecodes.I2F, "I2F"),
    I2D(Bytecodes.I2D, "I2D"),
    L2I(Bytecodes.L2I, "L2I"),
    L2F(Bytecodes.L2F, "L2F"),
    L2D(Bytecodes.L2D, "L2D"),
    F2I(Bytecodes.F2I, "F2I"),
    F2L(Bytecodes.F2L, "F2L"),
    F2D(Bytecodes.F2D, "F2D"),
    D2I(Bytecodes.D2I, "D2I"),
    D2L(Bytecodes.D2L, "D2L"),
    D2F(Bytecodes.D2F, "D2F"),
    I2B(Bytecodes.I2B, "I2B"),
    I2C(Bytecodes.I2C, "I2C"),
    I2S(Bytecodes.I2S, "I2S"),
    LCMP(Bytecodes.LCMP, "LCMP"),
    FCMPL(Bytecodes.FCMPL, "FCMPL"),
    FCMPG(Bytecodes.FCMPG, "FCMPG"),
    DCMPL(Bytecodes.DCMPL, "DCMPL"),
    DCMPG(Bytecodes.DCMPG, "DCMPG"),
    IFEQ(Bytecodes.IFEQ, "IFEQ"),
    IFNE(Bytecodes.IFNE, "IFNE"),
    IFLT(Bytecodes.IFLT, "IFLT"),
    IFGE(Bytecodes.IFGE, "IFGE"),
    IFGT(Bytecodes.IFGT, "IFGT"),
    IFLE(Bytecodes.IFLE, "IFLE"),
    IF_ICMPEQ(Bytecodes.IF_ICMPEQ, "IF_ICMPEQ"),
    IF_ICMPNE(Bytecodes.IF_ICMPNE, "IF_ICMPNE"),
    IF_ICMPLT(Bytecodes.IF_ICMPLT, "IF_ICMPLT"),
    IF_ICMPGE(Bytecodes.IF_ICMPGE, "IF_ICMPGE"),
    IF_ICMPGT(Bytecodes.IF_ICMPGT, "IF_ICMPGT"),
    IF_ICMPLE(Bytecodes.IF_ICMPLE, "IF_ICMPLE"),
    IF_ACMPEQ(Bytecodes.IF_ACMPEQ, "IF_ACMPEQ"),
    IF_ACMPNE(Bytecodes.IF_ACMPNE, "IF_ACMPNE"),
    GOTO(Bytecodes.GOTO, "GOTO"),
    JSR(Bytecodes.JSR, "JSR"),
    RET(Bytecodes.RET, "RET"),
    TABLESWITCH(Bytecodes.TABLESWITCH, "TABLESWITCH"),
    LOOKUPSWITCH(Bytecodes.LOOKUPSWITCH, "LOOKUPSWITCH"),
    IRETURN(Bytecodes.IRETURN, "IRETURN"),
    LRETURN(Bytecodes.LRETURN, "LRETURN"),
    FRETURN(Bytecodes.FRETURN, "FRETURN"),
    DRETURN(Bytecodes.DRETURN, "DRETURN"),
    ARETURN(Bytecodes.ARETURN, "ARETURN"),
    RETURN(Bytecodes.RETURN, "RETURN"),
    GETSTATIC(Bytecodes.GETSTATIC, "GetStatic"),
    PUTSTATIC(Bytecodes.PUTSTATIC, "PutStatic"),
    GETFIELD(Bytecodes.GETFIELD, "GetField"),
    PUTFIELD(Bytecodes.PUTFIELD, "PutField"),
    INVOKEVIRTUAL(Bytecodes.INVOKEVIRTUAL, "InvokeVirtual"),
    INVOKESPECIAL(Bytecodes.INVOKESPECIAL, "InvokeSpecial"),
    INVOKESTATIC(Bytecodes.INVOKESTATIC, "InvokeStatic"),
    INVOKEINTERFACE(Bytecodes.INVOKEINTERFACE, "InvokeInterface"),
    NEW(Bytecodes.NEW, "New"),
    NEWARRAY(Bytecodes.NEWARRAY, "NewArray"),
    ANEWARRAY(Bytecodes.ANEWARRAY, "NewArray"),
    ARRAYLENGTH(Bytecodes.ARRAYLENGTH, "ARRAYLENGTH"),
    ATHROW(Bytecodes.ATHROW, "ATHROW"),
    CHECKCAST(Bytecodes.CHECKCAST, "CHECKCAST"),
    INSTANCEOF(Bytecodes.INSTANCEOF, "INSTANCEOF"),
    MONITORENTER(Bytecodes.MONITORENTER, "MONITORENTER"),
    MONITOREXIT(Bytecodes.MONITOREXIT, "MONITOREXIT"),
    WIDE(Bytecodes.WIDE, "WIDE"),
    MULTIANEWARRAY(Bytecodes.MULTIANEWARRAY, "MultiNewArray"),
    IFNULL(Bytecodes.IFNULL, "IFNULL"),
    IFNONNULL(Bytecodes.IFNONNULL, "IFNONNULL"),
    GOTO_W(Bytecodes.GOTO_W, "GOTO_W"),
    JSR_W(Bytecodes.JSR_W, "JSR_W"),
    BREAKPOINT(Bytecodes.BREAKPOINT, "BREAKPOINT"),
    JNICALL(Bytecodes.JNICALL, "JNICALL"),
    JNIOP(Bytecodes.JNIOP, "JNIOP"),
    TEMPLATE_CALL(Bytecodes.TEMPLATE_CALL, "TEMPLATE_CALL"),
    WLOAD(Bytecodes.WLOAD, "WLOAD"),
    WLOAD_0(Bytecodes.WLOAD_0, "WLOAD_0"),
    WLOAD_1(Bytecodes.WLOAD_1, "WLOAD_1"),
    WLOAD_2(Bytecodes.WLOAD_2, "WLOAD_2"),
    WLOAD_3(Bytecodes.WLOAD_3, "WLOAD_3"),
    WSTORE(Bytecodes.WSTORE, "WSTORE"),
    WSTORE_0(Bytecodes.WSTORE_0, "WSTORE_0"),
    WSTORE_1(Bytecodes.WSTORE_1, "WSTORE_1"),
    WSTORE_2(Bytecodes.WSTORE_2, "WSTORE_2"),
    WSTORE_3(Bytecodes.WSTORE_3, "WSTORE_3"),
    WCONST_0(Bytecodes.WCONST_0, "WCONST_0"),
    WDIV(Bytecodes.WDIV, "WDIV"),
    WDIVI(Bytecodes.WDIVI, "WDIVI"),
    WREM(Bytecodes.WREM, "WREM"),
    WREMI(Bytecodes.WREMI, "WREMI"),
    ICMP(Bytecodes.ICMP, "ICMP"),
    WCMP(Bytecodes.WCMP, "WCMP"),
    PREAD(Bytecodes.PREAD, "PREAD"),
    PWRITE(Bytecodes.PWRITE, "PWRITE"),
    PGET(Bytecodes.PGET, "PGET"),
    PSET(Bytecodes.PSET, "PSET"),
    PCMPSWP(Bytecodes.PCMPSWP, "PCMPSWP"),
    MOV_I2F(Bytecodes.MOV_I2F, "MOV_I2F"),
    MOV_F2I(Bytecodes.MOV_F2I, "MOV_F2I"),
    MOV_L2D(Bytecodes.MOV_L2D, "MOV_L2D"),
    MOV_D2L(Bytecodes.MOV_D2L, "MOV_D2L"),
    UCMP(Bytecodes.UCMP, "UCMP"),
    UWCMP(Bytecodes.UWCMP, "UWCMP"),
    READREG(Bytecodes.READREG, "READREG"),
    WRITEREG(Bytecodes.WRITEREG, "WRITEREG"),
    INCREG(Bytecodes.INCREG, "INCREG"),
    UNSAFE_CAST(Bytecodes.UNSAFE_CAST, "UNSAFE_CAST"),
    WRETURN(Bytecodes.WRETURN, "WRETURN"),
    INFOPOINT(Bytecodes.INFOPOINT, "INFOPOINT"),
    SAFEPOINT(Bytecodes.SAFEPOINT, "SAFEPOINT"),
    HERE(Bytecodes.HERE, "HERE"),
    INFO(Bytecodes.INFO, "INFO"),
    ALLOCA(Bytecodes.ALLOCA, "ALLOCA"),
    MEMBAR(Bytecodes.MEMBAR, "MEMBAR"),
    STACKHANDLE(Bytecodes.STACKHANDLE, "STACKHANDLE"),
    PAUSE(Bytecodes.PAUSE, "PAUSE"),
    BREAKPOINT_TRAP(Bytecodes.BREAKPOINT_TRAP, "BREAKPOINT_TRAP"),
    ADD_SP(Bytecodes.ADD_SP, "ADD_SP"),
    FLUSHW(Bytecodes.FLUSHW, "FLUSHW"),
    LSB(Bytecodes.LSB, "LSB"),
    MSB(Bytecodes.MSB, "MSB"),
    PCMPSWP_INT(Bytecodes.PCMPSWP_INT, "PCMPSWP_INT"),
    PCMPSWP_LONG(Bytecodes.PCMPSWP_LONG, "PCMPSWP_LONG"),
    PCMPSWP_WORD(Bytecodes.PCMPSWP_WORD, "PCMPSWP_WORD"),
    PCMPSWP_REFERENCE(Bytecodes.PCMPSWP_REFERENCE, "PCMPSWP_REFERENCE"),
    PCMPSWP_INT_I(Bytecodes.PCMPSWP_INT_I, "PCMPSWP_INT_I"),
    PCMPSWP_LONG_I(Bytecodes.PCMPSWP_LONG_I, "PCMPSWP_LONG_I"),
    PCMPSWP_WORD_I(Bytecodes.PCMPSWP_WORD_I, "PCMPSWP_WORD_I"),
    PCMPSWP_REFERENCE_I(Bytecodes.PCMPSWP_REFERENCE_I, "PCMPSWP_REFERENCE_I"),
    PREAD_BYTE(Bytecodes.PREAD_BYTE, "PREAD_BYTE"),
    PREAD_CHAR(Bytecodes.PREAD_CHAR, "PREAD_CHAR"),
    PREAD_SHORT(Bytecodes.PREAD_SHORT, "PREAD_SHORT"),
    PREAD_INT(Bytecodes.PREAD_INT, "PREAD_INT"),
    PREAD_FLOAT(Bytecodes.PREAD_FLOAT, "PREAD_FLOAT"),
    PREAD_LONG(Bytecodes.PREAD_LONG, "PREAD_LONG"),
    PREAD_DOUBLE(Bytecodes.PREAD_DOUBLE, "PREAD_DOUBLE"),
    PREAD_WORD(Bytecodes.PREAD_WORD, "PREAD_WORD"),
    PREAD_REFERENCE(Bytecodes.PREAD_REFERENCE, "PREAD_REFERENCE"),
    PREAD_BYTE_I(Bytecodes.PREAD_BYTE_I, "PREAD_BYTE_I"),
    PREAD_CHAR_I(Bytecodes.PREAD_CHAR_I, "PREAD_CHAR_I"),
    PREAD_SHORT_I(Bytecodes.PREAD_SHORT_I, "PREAD_SHORT_I"),
    PREAD_INT_I(Bytecodes.PREAD_INT_I, "PREAD_INT_I"),
    PREAD_FLOAT_I(Bytecodes.PREAD_FLOAT_I, "PREAD_FLOAT_I"),
    PREAD_LONG_I(Bytecodes.PREAD_LONG_I, "PREAD_LONG_I"),
    PREAD_DOUBLE_I(Bytecodes.PREAD_DOUBLE_I, "PREAD_DOUBLE_I"),
    PREAD_WORD_I(Bytecodes.PREAD_WORD_I, "PREAD_WORD_I"),
    PREAD_REFERENCE_I(Bytecodes.PREAD_REFERENCE_I, "PREAD_REFERENCE_I"),
    PWRITE_BYTE(Bytecodes.PWRITE_BYTE, "PWRITE_BYTE"),
    PWRITE_SHORT(Bytecodes.PWRITE_SHORT, "PWRITE_SHORT"),
    PWRITE_INT(Bytecodes.PWRITE_INT, "PWRITE_INT"),
    PWRITE_FLOAT(Bytecodes.PWRITE_FLOAT, "PWRITE_FLOAT"),
    PWRITE_LONG(Bytecodes.PWRITE_LONG, "PWRITE_LONG"),
    PWRITE_DOUBLE(Bytecodes.PWRITE_DOUBLE, "PWRITE_DOUBLE"),
    PWRITE_WORD(Bytecodes.PWRITE_WORD, "PWRITE_WORD"),
    PWRITE_REFERENCE(Bytecodes.PWRITE_REFERENCE, "PWRITE_REFERENCE"),
    PWRITE_BYTE_I(Bytecodes.PWRITE_BYTE_I, "PWRITE_BYTE_I"),
    PWRITE_SHORT_I(Bytecodes.PWRITE_SHORT_I, "PWRITE_SHORT_I"),
    PWRITE_INT_I(Bytecodes.PWRITE_INT_I, "PWRITE_INT_I"),
    PWRITE_FLOAT_I(Bytecodes.PWRITE_FLOAT_I, "PWRITE_FLOAT_I"),
    PWRITE_LONG_I(Bytecodes.PWRITE_LONG_I, "PWRITE_LONG_I"),
    PWRITE_DOUBLE_I(Bytecodes.PWRITE_DOUBLE_I, "PWRITE_DOUBLE_I"),
    PWRITE_WORD_I(Bytecodes.PWRITE_WORD_I, "PWRITE_WORD_I"),
    PWRITE_REFERENCE_I(Bytecodes.PWRITE_REFERENCE_I, "PWRITE_REFERENCE_I"),
    PGET_BYTE(Bytecodes.PGET_BYTE, "PGET_BYTE"),
    PGET_CHAR(Bytecodes.PGET_CHAR, "PGET_CHAR"),
    PGET_SHORT(Bytecodes.PGET_SHORT, "PGET_SHORT"),
    PGET_INT(Bytecodes.PGET_INT, "PGET_INT"),
    PGET_FLOAT(Bytecodes.PGET_FLOAT, "PGET_FLOAT"),
    PGET_LONG(Bytecodes.PGET_LONG, "PGET_LONG"),
    PGET_DOUBLE(Bytecodes.PGET_DOUBLE, "PGET_DOUBLE"),
    PGET_WORD(Bytecodes.PGET_WORD, "PGET_WORD"),
    PGET_REFERENCE(Bytecodes.PGET_REFERENCE, "PGET_REFERENCE"),
    PSET_BYTE(Bytecodes.PSET_BYTE, "PSET_BYTE"),
    PSET_SHORT(Bytecodes.PSET_SHORT, "PSET_SHORT"),
    PSET_INT(Bytecodes.PSET_INT, "PSET_INT"),
    PSET_FLOAT(Bytecodes.PSET_FLOAT, "PSET_FLOAT"),
    PSET_LONG(Bytecodes.PSET_LONG, "PSET_LONG"),
    PSET_DOUBLE(Bytecodes.PSET_DOUBLE, "PSET_DOUBLE"),
    PSET_WORD(Bytecodes.PSET_WORD, "PSET_WORD"),
    PSET_REFERENCE(Bytecodes.PSET_REFERENCE, "PSET_REFERENCE"),
    MEMBAR_LOAD_LOAD(Bytecodes.MEMBAR_LOAD_LOAD, "MEMBAR_LOAD_LOAD"),
    MEMBAR_LOAD_STORE(Bytecodes.MEMBAR_LOAD_STORE, "MEMBAR_LOAD_STORE"),
    MEMBAR_STORE_LOAD(Bytecodes.MEMBAR_STORE_LOAD, "MEMBAR_STORE_LOAD"),
    MEMBAR_STORE_STORE(Bytecodes.MEMBAR_STORE_STORE, "MEMBAR_STORE_STORE"),
    JNIOP_LINK(Bytecodes.JNIOP_LINK, "JNIOP_LINK"),
    JNIOP_J2N(Bytecodes.JNIOP_J2N, "JNIOP_J2N"),
    JNIOP_N2J(Bytecodes.JNIOP_N2J, "JNIOP_N2J"),
    ILLEGAL(Bytecodes.ILLEGAL, "ILLEGAL"),
    END(Bytecodes.END, "END"),
    LAST_JVM_OPCODE(Bytecodes.LAST_JVM_OPCODE, "LAST_JVM_OPCODE");

    // END GENERATED CODE

    public final int code;
    public final String methodName;

    private VMABytecodes(int code, String methodName) {
        this.code = code;
        this.methodName = methodName;
    }

}
